/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Umbraco Management API
 * This shows all APIs available in this version of Umbraco - including all the legacy apis that are available for backward compatibility
 * OpenAPI spec version: Latest
 */
import type { ReferenceByIdModel } from './referenceByIdModel.js';
import type { AuditTypeModel } from './auditTypeModel.js';
import type { AuditLogResponseModelComment } from './auditLogResponseModelComment.js';
import type { AuditLogResponseModelParameters } from './auditLogResponseModelParameters.js';

export interface AuditLogResponseModel {
  user: ReferenceByIdModel;
  timestamp: string;
  logType: AuditTypeModel;
  comment?: AuditLogResponseModelComment;
  parameters?: AuditLogResponseModelParameters;
}
