/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Umbraco Management API
 * This shows all APIs available in this version of Umbraco - including all the legacy apis that are available for backward compatibility
 * OpenAPI spec version: Latest
 */
import type { CreateWebhookRequestModelId } from './createWebhookRequestModelId.js';
import type { CreateWebhookRequestModelName } from './createWebhookRequestModelName.js';
import type { CreateWebhookRequestModelDescription } from './createWebhookRequestModelDescription.js';
import type { CreateWebhookRequestModelHeaders } from './createWebhookRequestModelHeaders.js';

export interface CreateWebhookRequestModel {
  id?: CreateWebhookRequestModelId;
  events: string[];
  enabled: boolean;
  name?: CreateWebhookRequestModelName;
  description?: CreateWebhookRequestModelDescription;
  url: string;
  contentTypeKeys: string[];
  headers: CreateWebhookRequestModelHeaders;
}
