/**
 * Generated by orval v8.17.0 🍺
 * Do not edit manually.
 * Umbraco Management API
 * This shows all APIs available in this version of Umbraco - including all the legacy apis that are available for backward compatibility
 * OpenAPI spec version: Latest
 */
import type { IPermissionPresentationModel } from './iPermissionPresentationModel.js';
import type { ReferenceByIdModel } from './referenceByIdModel.js';

export interface CreateUserGroupRequestModel {
  /** @nullable */
  id?: string | null;
  name: string;
  alias: string;
  /** @nullable */
  description?: string | null;
  /** @nullable */
  icon?: string | null;
  sections: string[];
  languages: string[];
  hasAccessToAllLanguages: boolean;
  documentStartNode?: null | ReferenceByIdModel;
  documentRootAccess: boolean;
  mediaStartNode?: null | ReferenceByIdModel;
  mediaRootAccess: boolean;
  elementStartNode?: null | ReferenceByIdModel;
  elementRootAccess: boolean;
  fallbackPermissions: string[];
  permissions: IPermissionPresentationModel[];
}
