/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Umbraco Management API
 * This shows all APIs available in this version of Umbraco - including all the legacy apis that are available for backward compatibility
 * OpenAPI spec version: Latest
 */
import type { CreateDictionaryItemRequestModelId } from './createDictionaryItemRequestModelId.js';
import type { CreateDictionaryItemRequestModelParent } from './createDictionaryItemRequestModelParent.js';
import type { DictionaryItemTranslationModel } from './dictionaryItemTranslationModel.js';

export interface CreateDictionaryItemRequestModel {
  id?: CreateDictionaryItemRequestModelId;
  parent?: CreateDictionaryItemRequestModelParent;
  name: string;
  translations: DictionaryItemTranslationModel[];
}
