/**
 * Generated by orval v8.17.0 🍺
 * Do not edit manually.
 * Umbraco Management API
 * This shows all APIs available in this version of Umbraco - including all the legacy apis that are available for backward compatibility
 * OpenAPI spec version: Latest
 */
import type { CreateMediaTypePropertyTypeContainerRequestModel } from './createMediaTypePropertyTypeContainerRequestModel.js';
import type { CreateMediaTypePropertyTypeRequestModel } from './createMediaTypePropertyTypeRequestModel.js';
import type { MediaTypeCompositionModel } from './mediaTypeCompositionModel.js';
import type { MediaTypeSortModel } from './mediaTypeSortModel.js';
import type { ReferenceByIdModel } from './referenceByIdModel.js';

export interface CreateMediaTypeRequestModel {
  allowedMediaTypes: MediaTypeSortModel[];
  compositions: MediaTypeCompositionModel[];
  parent?: null | ReferenceByIdModel;
  /** @nullable */
  id?: string | null;
  alias: string;
  name: string;
  /** @nullable */
  description?: string | null;
  icon: string;
  allowedAsRoot: boolean;
  variesByCulture: boolean;
  variesBySegment: boolean;
  collection?: null | ReferenceByIdModel;
  isElement: boolean;
  allowedInLibrary: boolean;
  properties: CreateMediaTypePropertyTypeRequestModel[];
  containers: CreateMediaTypePropertyTypeContainerRequestModel[];
}
