/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Umbraco Management API
 * This shows all APIs available in this version of Umbraco - including all the legacy apis that are available for backward compatibility
 * OpenAPI spec version: Latest
 */
import type { MemberTypeCompositionModel } from './memberTypeCompositionModel.js';
import type { CreateMemberTypeRequestModelParent } from './createMemberTypeRequestModelParent.js';
import type { CreateMemberTypeRequestModelId } from './createMemberTypeRequestModelId.js';
import type { CreateMemberTypeRequestModelDescription } from './createMemberTypeRequestModelDescription.js';
import type { CreateMemberTypeRequestModelCollection } from './createMemberTypeRequestModelCollection.js';
import type { CreateMemberTypePropertyTypeRequestModel } from './createMemberTypePropertyTypeRequestModel.js';
import type { CreateMemberTypePropertyTypeContainerRequestModel } from './createMemberTypePropertyTypeContainerRequestModel.js';

export interface CreateMemberTypeRequestModel {
  compositions: MemberTypeCompositionModel[];
  parent?: CreateMemberTypeRequestModelParent;
  id?: CreateMemberTypeRequestModelId;
  alias: string;
  name: string;
  description?: CreateMemberTypeRequestModelDescription;
  icon: string;
  allowedAsRoot: boolean;
  variesByCulture: boolean;
  variesBySegment: boolean;
  collection?: CreateMemberTypeRequestModelCollection;
  isElement: boolean;
  allowedInLibrary: boolean;
  properties: CreateMemberTypePropertyTypeRequestModel[];
  containers: CreateMemberTypePropertyTypeContainerRequestModel[];
}
