/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Umbraco Management API
 * This shows all APIs available in this version of Umbraco - including all the legacy apis that are available for backward compatibility
 * OpenAPI spec version: Latest
 */
import type { ReferenceByIdModel } from './referenceByIdModel.js';
import type { CreateMemberRequestModelGroups } from './createMemberRequestModelGroups.js';
import type { CreateMemberRequestModelId } from './createMemberRequestModelId.js';
import type { MemberValueModel } from './memberValueModel.js';
import type { MemberVariantRequestModel } from './memberVariantRequestModel.js';

export interface CreateMemberRequestModel {
  email: string;
  username: string;
  password: string;
  memberType: ReferenceByIdModel;
  groups?: CreateMemberRequestModelGroups;
  isApproved: boolean;
  id?: CreateMemberRequestModelId;
  values: MemberValueModel[];
  variants: MemberVariantRequestModel[];
}
