/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Umbraco Management API
 * This shows all APIs available in this version of Umbraco - including all the legacy apis that are available for backward compatibility
 * OpenAPI spec version: Latest
 */
import type { CreateDataTypeRequestModelId } from './createDataTypeRequestModelId.js';
import type { CreateDataTypeRequestModelParent } from './createDataTypeRequestModelParent.js';
import type { DataTypePropertyPresentationModel } from './dataTypePropertyPresentationModel.js';

export interface CreateDataTypeRequestModel {
  id?: CreateDataTypeRequestModelId;
  parent?: CreateDataTypeRequestModelParent;
  name: string;
  editorAlias: string;
  editorUiAlias: string;
  values: DataTypePropertyPresentationModel[];
}
