/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Umbraco Management API
 * This shows all APIs available in this version of Umbraco - including all the legacy apis that are available for backward compatibility
 * OpenAPI spec version: Latest
 */
import type { CreateDocumentRequestModelTemplate } from './createDocumentRequestModelTemplate.js';
import type { ReferenceByIdModel } from './referenceByIdModel.js';
import type { CreateDocumentRequestModelParent } from './createDocumentRequestModelParent.js';
import type { CreateDocumentRequestModelId } from './createDocumentRequestModelId.js';
import type { DocumentValueModel } from './documentValueModel.js';
import type { DocumentVariantRequestModel } from './documentVariantRequestModel.js';

export interface CreateDocumentRequestModel {
  template: CreateDocumentRequestModelTemplate;
  documentType: ReferenceByIdModel;
  parent?: CreateDocumentRequestModelParent;
  id?: CreateDocumentRequestModelId;
  values: DocumentValueModel[];
  variants: DocumentVariantRequestModel[];
}
