/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Umbraco Management API
 * This shows all APIs available in this version of Umbraco - including all the legacy apis that are available for backward compatibility
 * OpenAPI spec version: Latest
 */
import type { ReferenceByIdModel } from './referenceByIdModel.js';
import type { CreateMediaRequestModelParent } from './createMediaRequestModelParent.js';
import type { CreateMediaRequestModelId } from './createMediaRequestModelId.js';
import type { MediaValueModel } from './mediaValueModel.js';
import type { MediaVariantRequestModel } from './mediaVariantRequestModel.js';

export interface CreateMediaRequestModel {
  mediaType: ReferenceByIdModel;
  parent?: CreateMediaRequestModelParent;
  id?: CreateMediaRequestModelId;
  values: MediaValueModel[];
  variants: MediaVariantRequestModel[];
}
