/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Umbraco Management API
 * This shows all APIs available in this version of Umbraco - including all the legacy apis that are available for backward compatibility
 * OpenAPI spec version: Latest
 */
import type { MediaTypeSortModel } from './mediaTypeSortModel.js';
import type { MediaTypeCompositionModel } from './mediaTypeCompositionModel.js';
import type { CreateMediaTypeRequestModelParent } from './createMediaTypeRequestModelParent.js';
import type { CreateMediaTypeRequestModelId } from './createMediaTypeRequestModelId.js';
import type { CreateMediaTypeRequestModelDescription } from './createMediaTypeRequestModelDescription.js';
import type { CreateMediaTypeRequestModelCollection } from './createMediaTypeRequestModelCollection.js';
import type { CreateMediaTypePropertyTypeRequestModel } from './createMediaTypePropertyTypeRequestModel.js';
import type { CreateMediaTypePropertyTypeContainerRequestModel } from './createMediaTypePropertyTypeContainerRequestModel.js';

export interface CreateMediaTypeRequestModel {
  allowedMediaTypes: MediaTypeSortModel[];
  compositions: MediaTypeCompositionModel[];
  parent?: CreateMediaTypeRequestModelParent;
  id?: CreateMediaTypeRequestModelId;
  alias: string;
  name: string;
  description?: CreateMediaTypeRequestModelDescription;
  icon: string;
  allowedAsRoot: boolean;
  variesByCulture: boolean;
  variesBySegment: boolean;
  collection?: CreateMediaTypeRequestModelCollection;
  isElement: boolean;
  allowedInLibrary: boolean;
  properties: CreateMediaTypePropertyTypeRequestModel[];
  containers: CreateMediaTypePropertyTypeContainerRequestModel[];
}
