/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Umbraco Management API
 * This shows all APIs available in this version of Umbraco - including all the legacy apis that are available for backward compatibility
 * OpenAPI spec version: Latest
 */
import type { ReferenceByIdModel } from './referenceByIdModel.js';
import type { CreateElementRequestModelParent } from './createElementRequestModelParent.js';
import type { CreateElementRequestModelId } from './createElementRequestModelId.js';
import type { ElementValueModel } from './elementValueModel.js';
import type { ElementVariantRequestModel } from './elementVariantRequestModel.js';

export interface CreateElementRequestModel {
  documentType: ReferenceByIdModel;
  parent?: CreateElementRequestModelParent;
  id?: CreateElementRequestModelId;
  values: ElementValueModel[];
  variants: ElementVariantRequestModel[];
}
