/**
 * Generated by orval v8.17.0 🍺
 * Do not edit manually.
 * Umbraco Management API
 * This shows all APIs available in this version of Umbraco - including all the legacy apis that are available for backward compatibility
 * OpenAPI spec version: Latest
 */
import type { ReferenceByIdModel } from './referenceByIdModel.js';

export interface CreateDocumentBlueprintFromDocumentRequestModel {
  document: ReferenceByIdModel;
  /** @nullable */
  id?: string | null;
  name: string;
  parent?: null | ReferenceByIdModel;
}
