/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Umbraco Management API
 * This shows all APIs available in this version of Umbraco - including all the legacy apis that are available for backward compatibility
 * OpenAPI spec version: Latest
 */
import type { CreatePackageRequestModelId } from './createPackageRequestModelId.js';
import type { CreatePackageRequestModelContentNodeId } from './createPackageRequestModelContentNodeId.js';

export interface CreatePackageRequestModel {
  id?: CreatePackageRequestModelId;
  name: string;
  contentNodeId?: CreatePackageRequestModelContentNodeId;
  contentLoadChildNodes: boolean;
  mediaIds: string[];
  mediaLoadChildNodes: boolean;
  documentTypes: string[];
  mediaTypes: string[];
  dataTypes: string[];
  templates: string[];
  partialViews: string[];
  stylesheets: string[];
  scripts: string[];
  languages: string[];
  dictionaryItems: string[];
}
