/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Umbraco Management API
 * This shows all APIs available in this version of Umbraco - including all the legacy apis that are available for backward compatibility
 * OpenAPI spec version: Latest
 */
import type { CreateMemberTypePropertyTypeContainerRequestModelParent } from './createMemberTypePropertyTypeContainerRequestModelParent.js';
import type { CreateMemberTypePropertyTypeContainerRequestModelName } from './createMemberTypePropertyTypeContainerRequestModelName.js';

export interface CreateMemberTypePropertyTypeContainerRequestModel {
  id: string;
  parent?: CreateMemberTypePropertyTypeContainerRequestModelParent;
  name?: CreateMemberTypePropertyTypeContainerRequestModelName;
  type: string;
  sortOrder: number;
}
