/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Umbraco Management API
 * This shows all APIs available in this version of Umbraco - including all the legacy apis that are available for backward compatibility
 * OpenAPI spec version: Latest
 */
import type { CreateMediaTypePropertyTypeContainerRequestModelParent } from './createMediaTypePropertyTypeContainerRequestModelParent.js';
import type { CreateMediaTypePropertyTypeContainerRequestModelName } from './createMediaTypePropertyTypeContainerRequestModelName.js';

export interface CreateMediaTypePropertyTypeContainerRequestModel {
  id: string;
  parent?: CreateMediaTypePropertyTypeContainerRequestModelParent;
  name?: CreateMediaTypePropertyTypeContainerRequestModelName;
  type: string;
  sortOrder: number;
}
