/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Umbraco Management API
 * This shows all APIs available in this version of Umbraco - including all the legacy apis that are available for backward compatibility
 * OpenAPI spec version: Latest
 */
import type { CurrentUserResponseModelLanguageIsoCode } from './currentUserResponseModelLanguageIsoCode.js';
import type { ReferenceByIdModel } from './referenceByIdModel.js';
import type { IPermissionPresentationModel } from './iPermissionPresentationModel.js';

export interface CurrentUserResponseModel {
  id: string;
  languageIsoCode: CurrentUserResponseModelLanguageIsoCode;
  documentStartNodeIds: ReferenceByIdModel[];
  hasDocumentRootAccess: boolean;
  mediaStartNodeIds: ReferenceByIdModel[];
  hasMediaRootAccess: boolean;
  elementStartNodeIds: ReferenceByIdModel[];
  hasElementRootAccess: boolean;
  avatarUrls: string[];
  languages: string[];
  hasAccessToAllLanguages: boolean;
  hasAccessToSensitiveData: boolean;
  fallbackPermissions: string[];
  permissions: IPermissionPresentationModel[];
  allowedSections: string[];
  isAdmin: boolean;
  email: string;
  userName: string;
  name: string;
  userGroupIds: ReferenceByIdModel[];
}
