/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Umbraco Management API
 * This shows all APIs available in this version of Umbraco - including all the legacy apis that are available for backward compatibility
 * OpenAPI spec version: Latest
 */
import type { DatabaseInstallRequestModelProviderName } from './databaseInstallRequestModelProviderName.js';
import type { DatabaseInstallRequestModelServer } from './databaseInstallRequestModelServer.js';
import type { DatabaseInstallRequestModelName } from './databaseInstallRequestModelName.js';
import type { DatabaseInstallRequestModelUsername } from './databaseInstallRequestModelUsername.js';
import type { DatabaseInstallRequestModelPassword } from './databaseInstallRequestModelPassword.js';
import type { DatabaseInstallRequestModelConnectionString } from './databaseInstallRequestModelConnectionString.js';

export interface DatabaseInstallRequestModel {
  id: string;
  providerName: DatabaseInstallRequestModelProviderName;
  server?: DatabaseInstallRequestModelServer;
  name?: DatabaseInstallRequestModelName;
  username?: DatabaseInstallRequestModelUsername;
  password?: DatabaseInstallRequestModelPassword;
  useIntegratedAuthentication: boolean;
  connectionString?: DatabaseInstallRequestModelConnectionString;
  trustServerCertificate: boolean;
}
