/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Umbraco Management API
 * This shows all APIs available in this version of Umbraco - including all the legacy apis that are available for backward compatibility
 * OpenAPI spec version: Latest
 */
import type { DataTypeSchemaResponseModelValueTypeName } from './dataTypeSchemaResponseModelValueTypeName.js';
import type { DataTypeSchemaResponseModelJsonSchema } from './dataTypeSchemaResponseModelJsonSchema.js';

export interface DataTypeSchemaResponseModel {
  valueTypeName?: DataTypeSchemaResponseModelValueTypeName;
  jsonSchema?: DataTypeSchemaResponseModelJsonSchema;
}
