/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Umbraco Management API
 * This shows all APIs available in this version of Umbraco - including all the legacy apis that are available for backward compatibility
 * OpenAPI spec version: Latest
 */
import type { DataTypeTreeItemResponseModelEditorUiAlias } from './dataTypeTreeItemResponseModelEditorUiAlias.js';
import type { DataTypeTreeItemResponseModelParent } from './dataTypeTreeItemResponseModelParent.js';
import type { FlagModel } from './flagModel.js';

export interface DataTypeTreeItemResponseModel {
  editorUiAlias?: DataTypeTreeItemResponseModelEditorUiAlias;
  isDeletable: boolean;
  isFolder: boolean;
  noAccess: boolean;
  name: string;
  id: string;
  parent?: DataTypeTreeItemResponseModelParent;
  flags: FlagModel[];
  hasChildren: boolean;
}
