/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Umbraco Management API
 * This shows all APIs available in this version of Umbraco - including all the legacy apis that are available for backward compatibility
 * OpenAPI spec version: Latest
 */
import type { DataTypeSchemaItemResponseModelValueTypeName } from './dataTypeSchemaItemResponseModelValueTypeName.js';
import type { DataTypeSchemaItemResponseModelJsonSchema } from './dataTypeSchemaItemResponseModelJsonSchema.js';
import type { DataTypeSchemaItemResponseModelError } from './dataTypeSchemaItemResponseModelError.js';

export interface DataTypeSchemaItemResponseModel {
  id: string;
  valueTypeName?: DataTypeSchemaItemResponseModelValueTypeName;
  jsonSchema?: DataTypeSchemaItemResponseModelJsonSchema;
  error?: DataTypeSchemaItemResponseModelError;
}
