/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Umbraco Management API
 * This shows all APIs available in this version of Umbraco - including all the legacy apis that are available for backward compatibility
 * OpenAPI spec version: Latest
 */

export interface DatabaseSettingsPresentationModel {
  id: string;
  sortOrder: number;
  displayName: string;
  defaultDatabaseName: string;
  providerName: string;
  isConfigured: boolean;
  requiresServer: boolean;
  serverPlaceholder: string;
  requiresCredentials: boolean;
  supportsIntegratedAuthentication: boolean;
  supportsTrustServerCertificate: boolean;
  requiresConnectionTest: boolean;
}
