/**
 * Generated by orval v8.17.0 🍺
 * Do not edit manually.
 * Umbraco Management API
 * This shows all APIs available in this version of Umbraco - including all the legacy apis that are available for backward compatibility
 * OpenAPI spec version: Latest
 */

export type DataTypeChangeModeModel = typeof DataTypeChangeModeModel[keyof typeof DataTypeChangeModeModel];


export const DataTypeChangeModeModel = {
  True: 'True',
  False: 'False',
  FalseWithHelpText: 'FalseWithHelpText',
} as const;
