/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Umbraco Management API
 * This shows all APIs available in this version of Umbraco - including all the legacy apis that are available for backward compatibility
 * OpenAPI spec version: Latest
 */
import type { FlagModel } from './flagModel.js';
import type { PublishableVariantStateModel } from './publishableVariantStateModel.js';
import type { DocumentVariantResponseModelPublishDate } from './documentVariantResponseModelPublishDate.js';
import type { DocumentVariantResponseModelScheduledPublishDate } from './documentVariantResponseModelScheduledPublishDate.js';
import type { DocumentVariantResponseModelScheduledUnpublishDate } from './documentVariantResponseModelScheduledUnpublishDate.js';
import type { DocumentVariantResponseModelCulture } from './documentVariantResponseModelCulture.js';
import type { DocumentVariantResponseModelSegment } from './documentVariantResponseModelSegment.js';

export interface DocumentVariantResponseModel {
  id: string;
  flags: FlagModel[];
  state: PublishableVariantStateModel;
  publishDate?: DocumentVariantResponseModelPublishDate;
  scheduledPublishDate?: DocumentVariantResponseModelScheduledPublishDate;
  scheduledUnpublishDate?: DocumentVariantResponseModelScheduledUnpublishDate;
  createDate: string;
  updateDate: string;
  culture?: DocumentVariantResponseModelCulture;
  segment?: DocumentVariantResponseModelSegment;
  name: string;
}
