/**
 * Generated by orval v8.17.0 🍺
 * Do not edit manually.
 * Umbraco Management API
 * This shows all APIs available in this version of Umbraco - including all the legacy apis that are available for backward compatibility
 * OpenAPI spec version: Latest
 */
import type { DocumentTypeReferenceResponseModel } from './documentTypeReferenceResponseModel.js';
import type { FlagModel } from './flagModel.js';

export interface DocumentBlueprintItemResponseModel {
  documentType: DocumentTypeReferenceResponseModel;
  name: string;
  id: string;
  flags: FlagModel[];
}
