/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Umbraco Management API
 * This shows all APIs available in this version of Umbraco - including all the legacy apis that are available for backward compatibility
 * OpenAPI spec version: Latest
 */
import type { DocumentValueResponseModelCulture } from './documentValueResponseModelCulture.js';
import type { DocumentValueResponseModelSegment } from './documentValueResponseModelSegment.js';

export interface DocumentValueResponseModel {
  editorAlias: string;
  culture?: DocumentValueResponseModelCulture;
  segment?: DocumentValueResponseModelSegment;
  alias: string;
  value?: unknown;
}
