/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Umbraco Management API
 * This shows all APIs available in this version of Umbraco - including all the legacy apis that are available for backward compatibility
 * OpenAPI spec version: Latest
 */
import type { DocumentValueModelCulture } from './documentValueModelCulture.js';
import type { DocumentValueModelSegment } from './documentValueModelSegment.js';

export interface DocumentValueModel {
  culture?: DocumentValueModelCulture;
  segment?: DocumentValueModelSegment;
  alias: string;
  value?: unknown;
}
