/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Umbraco Management API
 * This shows all APIs available in this version of Umbraco - including all the legacy apis that are available for backward compatibility
 * OpenAPI spec version: Latest
 */
import type { DocumentTypeCollectionReferenceResponseModel } from './documentTypeCollectionReferenceResponseModel.js';
import type { ReferenceByIdModel } from './referenceByIdModel.js';
import type { DocumentCollectionResponseModelUpdater } from './documentCollectionResponseModelUpdater.js';
import type { DocumentCollectionResponseModelCreator } from './documentCollectionResponseModelCreator.js';
import type { FlagModel } from './flagModel.js';
import type { DocumentValueResponseModel } from './documentValueResponseModel.js';
import type { DocumentVariantResponseModel } from './documentVariantResponseModel.js';

export interface DocumentCollectionResponseModel {
  documentType: DocumentTypeCollectionReferenceResponseModel;
  isTrashed: boolean;
  isProtected: boolean;
  ancestors: ReferenceByIdModel[];
  updater?: DocumentCollectionResponseModelUpdater;
  creator?: DocumentCollectionResponseModelCreator;
  sortOrder: number;
  id: string;
  flags: FlagModel[];
  values: DocumentValueResponseModel[];
  variants: DocumentVariantResponseModel[];
}
