/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Umbraco Management API
 * This shows all APIs available in this version of Umbraco - including all the legacy apis that are available for backward compatibility
 * OpenAPI spec version: Latest
 */
import type { DocumentUrlInfoModelMessage } from './documentUrlInfoModelMessage.js';
import type { DocumentUrlInfoModelCulture } from './documentUrlInfoModelCulture.js';
import type { DocumentUrlInfoModelUrl } from './documentUrlInfoModelUrl.js';

export interface DocumentUrlInfoModel {
  message: DocumentUrlInfoModelMessage;
  provider: string;
  culture: DocumentUrlInfoModelCulture;
  url: DocumentUrlInfoModelUrl;
}
