/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Umbraco Management API
 * This shows all APIs available in this version of Umbraco - including all the legacy apis that are available for backward compatibility
 * OpenAPI spec version: Latest
 */
import type { FlagModel } from './flagModel.js';
import type { PublishableVariantStateModel } from './publishableVariantStateModel.js';
import type { DocumentVariantItemResponseModelCulture } from './documentVariantItemResponseModelCulture.js';

export interface DocumentVariantItemResponseModel {
  id: string;
  flags: FlagModel[];
  state: PublishableVariantStateModel;
  name: string;
  culture?: DocumentVariantItemResponseModelCulture;
}
