/**
 * Generated by orval v8.17.0 🍺
 * Do not edit manually.
 * Umbraco Management API
 * This shows all APIs available in this version of Umbraco - including all the legacy apis that are available for backward compatibility
 * OpenAPI spec version: Latest
 */
import type { FlagModel } from './flagModel.js';
import type { ReferenceByIdModel } from './referenceByIdModel.js';

export interface DocumentTypeTreeItemResponseModel {
  isElement: boolean;
  icon: string;
  isFolder: boolean;
  noAccess: boolean;
  name: string;
  id: string;
  parent?: null | ReferenceByIdModel;
  flags: FlagModel[];
  hasChildren: boolean;
}
