/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Umbraco Management API
 * This shows all APIs available in this version of Umbraco - including all the legacy apis that are available for backward compatibility
 * OpenAPI spec version: Latest
 */
import type { DocumentTypeItemResponseModelIcon } from './documentTypeItemResponseModelIcon.js';
import type { DocumentTypeItemResponseModelDescription } from './documentTypeItemResponseModelDescription.js';
import type { FlagModel } from './flagModel.js';

export interface DocumentTypeItemResponseModel {
  isElement: boolean;
  allowedInLibrary: boolean;
  icon?: DocumentTypeItemResponseModelIcon;
  description?: DocumentTypeItemResponseModelDescription;
  name: string;
  id: string;
  flags: FlagModel[];
}
