/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Umbraco Management API
 * This shows all APIs available in this version of Umbraco - including all the legacy apis that are available for backward compatibility
 * OpenAPI spec version: Latest
 */
import type { DocumentBlueprintTreeItemResponseModelDocumentType } from './documentBlueprintTreeItemResponseModelDocumentType.js';
import type { DocumentBlueprintTreeItemResponseModelParent } from './documentBlueprintTreeItemResponseModelParent.js';
import type { FlagModel } from './flagModel.js';

export interface DocumentBlueprintTreeItemResponseModel {
  documentType?: DocumentBlueprintTreeItemResponseModelDocumentType;
  isFolder: boolean;
  noAccess: boolean;
  name: string;
  id: string;
  parent?: DocumentBlueprintTreeItemResponseModelParent;
  flags: FlagModel[];
  hasChildren: boolean;
}
