/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Umbraco Management API
 * This shows all APIs available in this version of Umbraco - including all the legacy apis that are available for backward compatibility
 * OpenAPI spec version: Latest
 */
import type { DomainsResponseModelDefaultIsoCode } from './domainsResponseModelDefaultIsoCode.js';
import type { DomainPresentationModel } from './domainPresentationModel.js';

export interface DomainsResponseModel {
  defaultIsoCode?: DomainsResponseModelDefaultIsoCode;
  domains: DomainPresentationModel[];
}
