/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Umbraco Management API
 * This shows all APIs available in this version of Umbraco - including all the legacy apis that are available for backward compatibility
 * OpenAPI spec version: Latest
 */
import type { DynamicRootContextRequestModelId } from './dynamicRootContextRequestModelId.js';
import type { ReferenceByIdModel } from './referenceByIdModel.js';
import type { DynamicRootContextRequestModelCulture } from './dynamicRootContextRequestModelCulture.js';
import type { DynamicRootContextRequestModelSegment } from './dynamicRootContextRequestModelSegment.js';

export interface DynamicRootContextRequestModel {
  id?: DynamicRootContextRequestModelId;
  parent: ReferenceByIdModel;
  culture?: DynamicRootContextRequestModelCulture;
  segment?: DynamicRootContextRequestModelSegment;
}
