/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Umbraco Management API
 * This shows all APIs available in this version of Umbraco - including all the legacy apis that are available for backward compatibility
 * OpenAPI spec version: Latest
 */
import type { ElementRecycleBinItemResponseModelDocumentType } from './elementRecycleBinItemResponseModelDocumentType.js';
import type { ElementVariantItemResponseModel } from './elementVariantItemResponseModel.js';
import type { ElementRecycleBinItemResponseModelParent } from './elementRecycleBinItemResponseModelParent.js';

export interface ElementRecycleBinItemResponseModel {
  documentType?: ElementRecycleBinItemResponseModelDocumentType;
  variants: ElementVariantItemResponseModel[];
  isFolder: boolean;
  name: string;
  id: string;
  createDate: string;
  hasChildren: boolean;
  parent?: ElementRecycleBinItemResponseModelParent;
}
