/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Umbraco Management API
 * This shows all APIs available in this version of Umbraco - including all the legacy apis that are available for backward compatibility
 * OpenAPI spec version: Latest
 */
import type { ElementValueResponseModelCulture } from './elementValueResponseModelCulture.js';
import type { ElementValueResponseModelSegment } from './elementValueResponseModelSegment.js';

export interface ElementValueResponseModel {
  editorAlias: string;
  culture?: ElementValueResponseModelCulture;
  segment?: ElementValueResponseModelSegment;
  alias: string;
  value?: unknown;
}
