/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Umbraco Management API
 * This shows all APIs available in this version of Umbraco - including all the legacy apis that are available for backward compatibility
 * OpenAPI spec version: Latest
 */
import type { FlagModel } from './flagModel.js';
import type { PublishableVariantStateModel } from './publishableVariantStateModel.js';
import type { ElementVariantResponseModelPublishDate } from './elementVariantResponseModelPublishDate.js';
import type { ElementVariantResponseModelScheduledPublishDate } from './elementVariantResponseModelScheduledPublishDate.js';
import type { ElementVariantResponseModelScheduledUnpublishDate } from './elementVariantResponseModelScheduledUnpublishDate.js';
import type { ElementVariantResponseModelCulture } from './elementVariantResponseModelCulture.js';
import type { ElementVariantResponseModelSegment } from './elementVariantResponseModelSegment.js';

export interface ElementVariantResponseModel {
  id: string;
  flags: FlagModel[];
  state: PublishableVariantStateModel;
  publishDate?: ElementVariantResponseModelPublishDate;
  scheduledPublishDate?: ElementVariantResponseModelScheduledPublishDate;
  scheduledUnpublishDate?: ElementVariantResponseModelScheduledUnpublishDate;
  createDate: string;
  updateDate: string;
  culture?: ElementVariantResponseModelCulture;
  segment?: ElementVariantResponseModelSegment;
  name: string;
}
