/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Umbraco Management API
 * This shows all APIs available in this version of Umbraco - including all the legacy apis that are available for backward compatibility
 * OpenAPI spec version: Latest
 */
import type { ElementTreeItemResponseModelDocumentType } from './elementTreeItemResponseModelDocumentType.js';
import type { ElementVariantItemResponseModel } from './elementVariantItemResponseModel.js';
import type { ElementTreeItemResponseModelParent } from './elementTreeItemResponseModelParent.js';
import type { FlagModel } from './flagModel.js';

export interface ElementTreeItemResponseModel {
  createDate: string;
  documentType?: ElementTreeItemResponseModelDocumentType;
  variants: ElementVariantItemResponseModel[];
  isFolder: boolean;
  noAccess: boolean;
  name: string;
  id: string;
  parent?: ElementTreeItemResponseModelParent;
  flags: FlagModel[];
  hasChildren: boolean;
}
