/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Umbraco Management API
 * This shows all APIs available in this version of Umbraco - including all the legacy apis that are available for backward compatibility
 * OpenAPI spec version: Latest
 */
import type { ElementItemResponseModelParent } from './elementItemResponseModelParent.js';
import type { DocumentTypeReferenceResponseModel } from './documentTypeReferenceResponseModel.js';
import type { ElementVariantItemResponseModel } from './elementVariantItemResponseModel.js';
import type { FlagModel } from './flagModel.js';

export interface ElementItemResponseModel {
  isTrashed: boolean;
  parent?: ElementItemResponseModelParent;
  hasChildren: boolean;
  documentType: DocumentTypeReferenceResponseModel;
  variants: ElementVariantItemResponseModel[];
  id: string;
  flags: FlagModel[];
}
