/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Umbraco Management API
 * This shows all APIs available in this version of Umbraco - including all the legacy apis that are available for backward compatibility
 * OpenAPI spec version: Latest
 */
import type { StatusResultTypeModel } from './statusResultTypeModel.js';
import type { HealthCheckResultResponseModelActions } from './healthCheckResultResponseModelActions.js';
import type { HealthCheckResultResponseModelReadMoreLink } from './healthCheckResultResponseModelReadMoreLink.js';

export interface HealthCheckResultResponseModel {
  message: string;
  resultType: StatusResultTypeModel;
  actions?: HealthCheckResultResponseModelActions;
  readMoreLink?: HealthCheckResultResponseModelReadMoreLink;
}
