/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Umbraco Management API
 * This shows all APIs available in this version of Umbraco - including all the legacy apis that are available for backward compatibility
 * OpenAPI spec version: Latest
 */
import type { ReferenceByIdModel } from './referenceByIdModel.js';
import type { HealthCheckActionRequestModelAlias } from './healthCheckActionRequestModelAlias.js';
import type { HealthCheckActionRequestModelName } from './healthCheckActionRequestModelName.js';
import type { HealthCheckActionRequestModelDescription } from './healthCheckActionRequestModelDescription.js';
import type { HealthCheckActionRequestModelProvidedValue } from './healthCheckActionRequestModelProvidedValue.js';
import type { HealthCheckActionRequestModelProvidedValueValidation } from './healthCheckActionRequestModelProvidedValueValidation.js';
import type { HealthCheckActionRequestModelProvidedValueValidationRegex } from './healthCheckActionRequestModelProvidedValueValidationRegex.js';
import type { HealthCheckActionRequestModelActionParameters } from './healthCheckActionRequestModelActionParameters.js';

export interface HealthCheckActionRequestModel {
  healthCheck: ReferenceByIdModel;
  alias?: HealthCheckActionRequestModelAlias;
  name?: HealthCheckActionRequestModelName;
  description?: HealthCheckActionRequestModelDescription;
  valueRequired: boolean;
  providedValue?: HealthCheckActionRequestModelProvidedValue;
  providedValueValidation?: HealthCheckActionRequestModelProvidedValueValidation;
  providedValueValidationRegex?: HealthCheckActionRequestModelProvidedValueValidationRegex;
  actionParameters?: HealthCheckActionRequestModelActionParameters;
}
