/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Umbraco Management API
 * This shows all APIs available in this version of Umbraco - including all the legacy apis that are available for backward compatibility
 * OpenAPI spec version: Latest
 */
import type { HelpPageResponseModelName } from './helpPageResponseModelName.js';
import type { HelpPageResponseModelDescription } from './helpPageResponseModelDescription.js';
import type { HelpPageResponseModelUrl } from './helpPageResponseModelUrl.js';
import type { HelpPageResponseModelType } from './helpPageResponseModelType.js';

export interface HelpPageResponseModel {
  name?: HelpPageResponseModelName;
  description?: HelpPageResponseModelDescription;
  url?: HelpPageResponseModelUrl;
  type?: HelpPageResponseModelType;
}
