/**
 * Generated by orval v8.17.0 🍺
 * Do not edit manually.
 * Umbraco Management API
 * This shows all APIs available in this version of Umbraco - including all the legacy apis that are available for backward compatibility
 * OpenAPI spec version: Latest
 */
import type { DatabaseInstallRequestModel } from './databaseInstallRequestModel.js';
import type { TelemetryLevelModel } from './telemetryLevelModel.js';
import type { UserInstallRequestModel } from './userInstallRequestModel.js';

export interface InstallRequestModel {
  user: UserInstallRequestModel;
  database: DatabaseInstallRequestModel;
  telemetryLevel: TelemetryLevelModel;
}
