/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Umbraco Management API
 * This shows all APIs available in this version of Umbraco - including all the legacy apis that are available for backward compatibility
 * OpenAPI spec version: Latest
 */
import type { InviteUserRequestModelMessage } from './inviteUserRequestModelMessage.js';
import type { InviteUserRequestModelId } from './inviteUserRequestModelId.js';
import type { ReferenceByIdModel } from './referenceByIdModel.js';

export interface InviteUserRequestModel {
  message?: InviteUserRequestModelMessage;
  id?: InviteUserRequestModelId;
  email: string;
  userName: string;
  name: string;
  userGroupIds: ReferenceByIdModel[];
}
