/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Umbraco Management API
 * This shows all APIs available in this version of Umbraco - including all the legacy apis that are available for backward compatibility
 * OpenAPI spec version: Latest
 */
import type { IPermissionPresentationModelDocumentPermissionPresentationModel } from './iPermissionPresentationModelDocumentPermissionPresentationModel.js';
import type { IPermissionPresentationModelDocumentPropertyValuePermissionPresentationModel } from './iPermissionPresentationModelDocumentPropertyValuePermissionPresentationModel.js';
import type { IPermissionPresentationModelElementPermissionPresentationModel } from './iPermissionPresentationModelElementPermissionPresentationModel.js';
import type { IPermissionPresentationModelUnknownTypePermissionPresentationModel } from './iPermissionPresentationModelUnknownTypePermissionPresentationModel.js';

export type IPermissionPresentationModel = IPermissionPresentationModelDocumentPermissionPresentationModel | IPermissionPresentationModelDocumentPropertyValuePermissionPresentationModel | IPermissionPresentationModelElementPermissionPresentationModel | IPermissionPresentationModelUnknownTypePermissionPresentationModel;
