/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Umbraco Management API
 * This shows all APIs available in this version of Umbraco - including all the legacy apis that are available for backward compatibility
 * OpenAPI spec version: Latest
 */

export type IPermissionPresentationModelElementPermissionPresentationModelType = typeof IPermissionPresentationModelElementPermissionPresentationModelType[keyof typeof IPermissionPresentationModelElementPermissionPresentationModelType];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const IPermissionPresentationModelElementPermissionPresentationModelType = {
  ElementPermissionPresentationModel: 'ElementPermissionPresentationModel',
} as const;
