/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Umbraco Management API
 * This shows all APIs available in this version of Umbraco - including all the legacy apis that are available for backward compatibility
 * OpenAPI spec version: Latest
 */
import type { IReferenceResponseModelDefaultReferenceResponseModel } from './iReferenceResponseModelDefaultReferenceResponseModel.js';
import type { IReferenceResponseModelDocumentReferenceResponseModel } from './iReferenceResponseModelDocumentReferenceResponseModel.js';
import type { IReferenceResponseModelDocumentTypePropertyTypeReferenceResponseModel } from './iReferenceResponseModelDocumentTypePropertyTypeReferenceResponseModel.js';
import type { IReferenceResponseModelElementContainerReferenceResponseModel } from './iReferenceResponseModelElementContainerReferenceResponseModel.js';
import type { IReferenceResponseModelElementReferenceResponseModel } from './iReferenceResponseModelElementReferenceResponseModel.js';
import type { IReferenceResponseModelMediaReferenceResponseModel } from './iReferenceResponseModelMediaReferenceResponseModel.js';
import type { IReferenceResponseModelMediaTypePropertyTypeReferenceResponseModel } from './iReferenceResponseModelMediaTypePropertyTypeReferenceResponseModel.js';
import type { IReferenceResponseModelMemberReferenceResponseModel } from './iReferenceResponseModelMemberReferenceResponseModel.js';
import type { IReferenceResponseModelMemberTypePropertyTypeReferenceResponseModel } from './iReferenceResponseModelMemberTypePropertyTypeReferenceResponseModel.js';

export type IReferenceResponseModel = IReferenceResponseModelDefaultReferenceResponseModel | IReferenceResponseModelDocumentReferenceResponseModel | IReferenceResponseModelDocumentTypePropertyTypeReferenceResponseModel | IReferenceResponseModelElementContainerReferenceResponseModel | IReferenceResponseModelElementReferenceResponseModel | IReferenceResponseModelMediaReferenceResponseModel | IReferenceResponseModelMediaTypePropertyTypeReferenceResponseModel | IReferenceResponseModelMemberReferenceResponseModel | IReferenceResponseModelMemberTypePropertyTypeReferenceResponseModel;
