/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Umbraco Management API
 * This shows all APIs available in this version of Umbraco - including all the legacy apis that are available for backward compatibility
 * OpenAPI spec version: Latest
 */
import type { IReferenceResponseModelMemberReferenceResponseModelType } from './iReferenceResponseModelMemberReferenceResponseModelType.js';
import type { TrackedReferenceMemberTypeModel } from './trackedReferenceMemberTypeModel.js';
import type { IReferenceResponseModelMemberReferenceResponseModelName } from './iReferenceResponseModelMemberReferenceResponseModelName.js';

export interface IReferenceResponseModelMemberReferenceResponseModel {
  $type: IReferenceResponseModelMemberReferenceResponseModelType;
  memberType: TrackedReferenceMemberTypeModel;
  id: string;
  name?: IReferenceResponseModelMemberReferenceResponseModelName;
}
