/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Umbraco Management API
 * This shows all APIs available in this version of Umbraco - including all the legacy apis that are available for backward compatibility
 * OpenAPI spec version: Latest
 */
import type { IReferenceResponseModelElementReferenceResponseModelType } from './iReferenceResponseModelElementReferenceResponseModelType.js';
import type { IReferenceResponseModelElementReferenceResponseModelPublished } from './iReferenceResponseModelElementReferenceResponseModelPublished.js';
import type { TrackedReferenceDocumentTypeModel } from './trackedReferenceDocumentTypeModel.js';
import type { ElementVariantItemResponseModel } from './elementVariantItemResponseModel.js';
import type { IReferenceResponseModelElementReferenceResponseModelName } from './iReferenceResponseModelElementReferenceResponseModelName.js';

export interface IReferenceResponseModelElementReferenceResponseModel {
  $type: IReferenceResponseModelElementReferenceResponseModelType;
  published?: IReferenceResponseModelElementReferenceResponseModelPublished;
  documentType: TrackedReferenceDocumentTypeModel;
  variants: ElementVariantItemResponseModel[];
  id: string;
  name?: IReferenceResponseModelElementReferenceResponseModelName;
}
