/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Umbraco Management API
 * This shows all APIs available in this version of Umbraco - including all the legacy apis that are available for backward compatibility
 * OpenAPI spec version: Latest
 */
import type { IReferenceResponseModelDocumentTypePropertyTypeReferenceResponseModelType } from './iReferenceResponseModelDocumentTypePropertyTypeReferenceResponseModelType.js';
import type { TrackedReferenceDocumentTypeModel } from './trackedReferenceDocumentTypeModel.js';
import type { IReferenceResponseModelDocumentTypePropertyTypeReferenceResponseModelAlias } from './iReferenceResponseModelDocumentTypePropertyTypeReferenceResponseModelAlias.js';
import type { IReferenceResponseModelDocumentTypePropertyTypeReferenceResponseModelName } from './iReferenceResponseModelDocumentTypePropertyTypeReferenceResponseModelName.js';

export interface IReferenceResponseModelDocumentTypePropertyTypeReferenceResponseModel {
  $type: IReferenceResponseModelDocumentTypePropertyTypeReferenceResponseModelType;
  documentType: TrackedReferenceDocumentTypeModel;
  alias?: IReferenceResponseModelDocumentTypePropertyTypeReferenceResponseModelAlias;
  id: string;
  name?: IReferenceResponseModelDocumentTypePropertyTypeReferenceResponseModelName;
}
