/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Umbraco Management API
 * This shows all APIs available in this version of Umbraco - including all the legacy apis that are available for backward compatibility
 * OpenAPI spec version: Latest
 */
import type { IReferenceResponseModelMediaTypePropertyTypeReferenceResponseModelType } from './iReferenceResponseModelMediaTypePropertyTypeReferenceResponseModelType.js';
import type { TrackedReferenceMediaTypeModel } from './trackedReferenceMediaTypeModel.js';
import type { IReferenceResponseModelMediaTypePropertyTypeReferenceResponseModelAlias } from './iReferenceResponseModelMediaTypePropertyTypeReferenceResponseModelAlias.js';
import type { IReferenceResponseModelMediaTypePropertyTypeReferenceResponseModelName } from './iReferenceResponseModelMediaTypePropertyTypeReferenceResponseModelName.js';

export interface IReferenceResponseModelMediaTypePropertyTypeReferenceResponseModel {
  $type: IReferenceResponseModelMediaTypePropertyTypeReferenceResponseModelType;
  mediaType: TrackedReferenceMediaTypeModel;
  alias?: IReferenceResponseModelMediaTypePropertyTypeReferenceResponseModelAlias;
  id: string;
  name?: IReferenceResponseModelMediaTypePropertyTypeReferenceResponseModelName;
}
