/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Umbraco Management API
 * This shows all APIs available in this version of Umbraco - including all the legacy apis that are available for backward compatibility
 * OpenAPI spec version: Latest
 */
import type { IReferenceResponseModelDocumentReferenceResponseModelType } from './iReferenceResponseModelDocumentReferenceResponseModelType.js';
import type { IReferenceResponseModelDocumentReferenceResponseModelPublished } from './iReferenceResponseModelDocumentReferenceResponseModelPublished.js';
import type { TrackedReferenceDocumentTypeModel } from './trackedReferenceDocumentTypeModel.js';
import type { DocumentVariantItemResponseModel } from './documentVariantItemResponseModel.js';
import type { IReferenceResponseModelDocumentReferenceResponseModelName } from './iReferenceResponseModelDocumentReferenceResponseModelName.js';

export interface IReferenceResponseModelDocumentReferenceResponseModel {
  $type: IReferenceResponseModelDocumentReferenceResponseModelType;
  published?: IReferenceResponseModelDocumentReferenceResponseModelPublished;
  documentType: TrackedReferenceDocumentTypeModel;
  variants: DocumentVariantItemResponseModel[];
  id: string;
  name?: IReferenceResponseModelDocumentReferenceResponseModelName;
}
