/**
 * Generated by orval v8.17.0 🍺
 * Do not edit manually.
 * Umbraco Management API
 * This shows all APIs available in this version of Umbraco - including all the legacy apis that are available for backward compatibility
 * OpenAPI spec version: Latest
 */
import type { IReferenceResponseModelMediaTypePropertyTypeReferenceResponseModelType } from './iReferenceResponseModelMediaTypePropertyTypeReferenceResponseModelType.js';
import type { TrackedReferenceMediaTypeModel } from './trackedReferenceMediaTypeModel.js';

export interface IReferenceResponseModelMediaTypePropertyTypeReferenceResponseModel {
  $type: IReferenceResponseModelMediaTypePropertyTypeReferenceResponseModelType;
  mediaType: TrackedReferenceMediaTypeModel;
  /** @nullable */
  alias?: string | null;
  id: string;
  /** @nullable */
  name?: string | null;
}
