/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Umbraco Management API
 * This shows all APIs available in this version of Umbraco - including all the legacy apis that are available for backward compatibility
 * OpenAPI spec version: Latest
 */
import type { IReferenceResponseModelDefaultReferenceResponseModelType } from './iReferenceResponseModelDefaultReferenceResponseModelType.js';
import type { IReferenceResponseModelDefaultReferenceResponseModelIcon } from './iReferenceResponseModelDefaultReferenceResponseModelIcon.js';
import type { IReferenceResponseModelDefaultReferenceResponseModelName } from './iReferenceResponseModelDefaultReferenceResponseModelName.js';

export interface IReferenceResponseModelDefaultReferenceResponseModel {
  type?: IReferenceResponseModelDefaultReferenceResponseModelType;
  icon?: IReferenceResponseModelDefaultReferenceResponseModelIcon;
  id: string;
  name?: IReferenceResponseModelDefaultReferenceResponseModelName;
}
