/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Umbraco Management API
 * This shows all APIs available in this version of Umbraco - including all the legacy apis that are available for backward compatibility
 * OpenAPI spec version: Latest
 */
import type { LogLevelModel } from './logLevelModel.js';
import type { LogMessageResponseModelMessageTemplate } from './logMessageResponseModelMessageTemplate.js';
import type { LogMessageResponseModelRenderedMessage } from './logMessageResponseModelRenderedMessage.js';
import type { LogMessagePropertyPresentationModel } from './logMessagePropertyPresentationModel.js';
import type { LogMessageResponseModelException } from './logMessageResponseModelException.js';

export interface LogMessageResponseModel {
  timestamp: string;
  level: LogLevelModel;
  messageTemplate?: LogMessageResponseModelMessageTemplate;
  renderedMessage?: LogMessageResponseModelRenderedMessage;
  properties: LogMessagePropertyPresentationModel[];
  exception?: LogMessageResponseModelException;
}
