/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Umbraco Management API
 * This shows all APIs available in this version of Umbraco - including all the legacy apis that are available for backward compatibility
 * OpenAPI spec version: Latest
 */
import type { ManifestResponseModelId } from './manifestResponseModelId.js';
import type { ManifestResponseModelVersion } from './manifestResponseModelVersion.js';

export interface ManifestResponseModel {
  name: string;
  id?: ManifestResponseModelId;
  version?: ManifestResponseModelVersion;
  extensions: unknown[];
}
