/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Umbraco Management API
 * This shows all APIs available in this version of Umbraco - including all the legacy apis that are available for backward compatibility
 * OpenAPI spec version: Latest
 */
import type { MediaTypeReferenceResponseModel } from './mediaTypeReferenceResponseModel.js';
import type { VariantItemResponseModel } from './variantItemResponseModel.js';
import type { MediaTreeItemResponseModelParent } from './mediaTreeItemResponseModelParent.js';
import type { FlagModel } from './flagModel.js';

export interface MediaTreeItemResponseModel {
  mediaType: MediaTypeReferenceResponseModel;
  variants: VariantItemResponseModel[];
  noAccess: boolean;
  isTrashed: boolean;
  createDate: string;
  id: string;
  parent?: MediaTreeItemResponseModelParent;
  flags: FlagModel[];
  hasChildren: boolean;
}
