/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Umbraco Management API
 * This shows all APIs available in this version of Umbraco - including all the legacy apis that are available for backward compatibility
 * OpenAPI spec version: Latest
 */
import type { MediaTypePropertyTypeContainerResponseModelParent } from './mediaTypePropertyTypeContainerResponseModelParent.js';
import type { MediaTypePropertyTypeContainerResponseModelName } from './mediaTypePropertyTypeContainerResponseModelName.js';

export interface MediaTypePropertyTypeContainerResponseModel {
  id: string;
  parent?: MediaTypePropertyTypeContainerResponseModelParent;
  name?: MediaTypePropertyTypeContainerResponseModelName;
  type: string;
  sortOrder: number;
}
