/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Umbraco Management API
 * This shows all APIs available in this version of Umbraco - including all the legacy apis that are available for backward compatibility
 * OpenAPI spec version: Latest
 */
import type { MediaVariantResponseModelCulture } from './mediaVariantResponseModelCulture.js';
import type { MediaVariantResponseModelSegment } from './mediaVariantResponseModelSegment.js';

export interface MediaVariantResponseModel {
  createDate: string;
  updateDate: string;
  culture?: MediaVariantResponseModelCulture;
  segment?: MediaVariantResponseModelSegment;
  name: string;
}
