/**
 * Generated by orval v8.17.0 🍺
 * Do not edit manually.
 * Umbraco Management API
 * This shows all APIs available in this version of Umbraco - including all the legacy apis that are available for backward compatibility
 * OpenAPI spec version: Latest
 */
import type { FlagModel } from './flagModel.js';
import type { MediaTypeReferenceResponseModel } from './mediaTypeReferenceResponseModel.js';
import type { MediaValueResponseModel } from './mediaValueResponseModel.js';
import type { MediaVariantResponseModel } from './mediaVariantResponseModel.js';

export interface MediaResponseModel {
  isTrashed: boolean;
  mediaType: MediaTypeReferenceResponseModel;
  id: string;
  flags: FlagModel[];
  values: MediaValueResponseModel[];
  variants: MediaVariantResponseModel[];
}
