/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Umbraco Management API
 * This shows all APIs available in this version of Umbraco - including all the legacy apis that are available for backward compatibility
 * OpenAPI spec version: Latest
 */
import type { MediaValueModelCulture } from './mediaValueModelCulture.js';
import type { MediaValueModelSegment } from './mediaValueModelSegment.js';

export interface MediaValueModel {
  culture?: MediaValueModelCulture;
  segment?: MediaValueModelSegment;
  alias: string;
  value?: unknown;
}
