/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Umbraco Management API
 * This shows all APIs available in this version of Umbraco - including all the legacy apis that are available for backward compatibility
 * OpenAPI spec version: Latest
 */
import type { MediaTypeItemResponseModelIcon } from './mediaTypeItemResponseModelIcon.js';
import type { FlagModel } from './flagModel.js';

export interface MediaTypeItemResponseModel {
  icon?: MediaTypeItemResponseModelIcon;
  name: string;
  id: string;
  flags: FlagModel[];
}
