/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Umbraco Management API
 * This shows all APIs available in this version of Umbraco - including all the legacy apis that are available for backward compatibility
 * OpenAPI spec version: Latest
 */
import type { MediaTypeCollectionReferenceResponseModel } from './mediaTypeCollectionReferenceResponseModel.js';
import type { MediaCollectionResponseModelCreator } from './mediaCollectionResponseModelCreator.js';
import type { FlagModel } from './flagModel.js';
import type { MediaValueResponseModel } from './mediaValueResponseModel.js';
import type { MediaVariantResponseModel } from './mediaVariantResponseModel.js';

export interface MediaCollectionResponseModel {
  mediaType: MediaTypeCollectionReferenceResponseModel;
  creator?: MediaCollectionResponseModelCreator;
  sortOrder: number;
  id: string;
  flags: FlagModel[];
  values: MediaValueResponseModel[];
  variants: MediaVariantResponseModel[];
}
