/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Umbraco Management API
 * This shows all APIs available in this version of Umbraco - including all the legacy apis that are available for backward compatibility
 * OpenAPI spec version: Latest
 */
import type { MediaTypePropertyTypeResponseModelContainer } from './mediaTypePropertyTypeResponseModelContainer.js';
import type { MediaTypePropertyTypeResponseModelDescription } from './mediaTypePropertyTypeResponseModelDescription.js';
import type { ReferenceByIdModel } from './referenceByIdModel.js';
import type { PropertyTypeValidationModel } from './propertyTypeValidationModel.js';
import type { PropertyTypeAppearanceModel } from './propertyTypeAppearanceModel.js';

export interface MediaTypePropertyTypeResponseModel {
  id: string;
  container?: MediaTypePropertyTypeResponseModelContainer;
  sortOrder: number;
  alias: string;
  name: string;
  description?: MediaTypePropertyTypeResponseModelDescription;
  dataType: ReferenceByIdModel;
  variesByCulture: boolean;
  variesBySegment: boolean;
  validation: PropertyTypeValidationModel;
  appearance: PropertyTypeAppearanceModel;
}
