/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Umbraco Management API
 * This shows all APIs available in this version of Umbraco - including all the legacy apis that are available for backward compatibility
 * OpenAPI spec version: Latest
 */
import type { MediaVariantRequestModelCulture } from './mediaVariantRequestModelCulture.js';
import type { MediaVariantRequestModelSegment } from './mediaVariantRequestModelSegment.js';

export interface MediaVariantRequestModel {
  culture?: MediaVariantRequestModelCulture;
  segment?: MediaVariantRequestModelSegment;
  name: string;
}
