/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Umbraco Management API
 * This shows all APIs available in this version of Umbraco - including all the legacy apis that are available for backward compatibility
 * OpenAPI spec version: Latest
 */
import type { MediaValueResponseModelCulture } from './mediaValueResponseModelCulture.js';
import type { MediaValueResponseModelSegment } from './mediaValueResponseModelSegment.js';

export interface MediaValueResponseModel {
  editorAlias: string;
  culture?: MediaValueResponseModelCulture;
  segment?: MediaValueResponseModelSegment;
  alias: string;
  value?: unknown;
}
