/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Umbraco Management API
 * This shows all APIs available in this version of Umbraco - including all the legacy apis that are available for backward compatibility
 * OpenAPI spec version: Latest
 */
import type { MemberValueResponseModelCulture } from './memberValueResponseModelCulture.js';
import type { MemberValueResponseModelSegment } from './memberValueResponseModelSegment.js';

export interface MemberValueResponseModel {
  editorAlias: string;
  culture?: MemberValueResponseModelCulture;
  segment?: MemberValueResponseModelSegment;
  alias: string;
  value?: unknown;
}
