/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Umbraco Management API
 * This shows all APIs available in this version of Umbraco - including all the legacy apis that are available for backward compatibility
 * OpenAPI spec version: Latest
 */
import type { MemberVariantRequestModelCulture } from './memberVariantRequestModelCulture.js';
import type { MemberVariantRequestModelSegment } from './memberVariantRequestModelSegment.js';

export interface MemberVariantRequestModel {
  culture?: MemberVariantRequestModelCulture;
  segment?: MemberVariantRequestModelSegment;
  name: string;
}
