/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Umbraco Management API
 * This shows all APIs available in this version of Umbraco - including all the legacy apis that are available for backward compatibility
 * OpenAPI spec version: Latest
 */
import type { MemberTypeTreeItemResponseModelParent } from './memberTypeTreeItemResponseModelParent.js';
import type { FlagModel } from './flagModel.js';

export interface MemberTypeTreeItemResponseModel {
  icon: string;
  isFolder: boolean;
  noAccess: boolean;
  name: string;
  id: string;
  parent?: MemberTypeTreeItemResponseModelParent;
  flags: FlagModel[];
  hasChildren: boolean;
}
