/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Umbraco Management API
 * This shows all APIs available in this version of Umbraco - including all the legacy apis that are available for backward compatibility
 * OpenAPI spec version: Latest
 */
import type { MemberTypeReferenceResponseModel } from './memberTypeReferenceResponseModel.js';
import type { MemberResponseModelLastLoginDate } from './memberResponseModelLastLoginDate.js';
import type { MemberResponseModelLastLockoutDate } from './memberResponseModelLastLockoutDate.js';
import type { MemberResponseModelLastPasswordChangeDate } from './memberResponseModelLastPasswordChangeDate.js';
import type { MemberKindModel } from './memberKindModel.js';
import type { MemberResponseModelProfileData } from './memberResponseModelProfileData.js';
import type { FlagModel } from './flagModel.js';
import type { MemberValueResponseModel } from './memberValueResponseModel.js';
import type { MemberVariantResponseModel } from './memberVariantResponseModel.js';

export interface MemberResponseModel {
  email: string;
  username: string;
  memberType: MemberTypeReferenceResponseModel;
  isApproved: boolean;
  isLockedOut: boolean;
  isTwoFactorEnabled: boolean;
  failedPasswordAttempts: number;
  lastLoginDate?: MemberResponseModelLastLoginDate;
  lastLockoutDate?: MemberResponseModelLastLockoutDate;
  lastPasswordChangeDate?: MemberResponseModelLastPasswordChangeDate;
  groups: string[];
  kind: MemberKindModel;
  profileData?: MemberResponseModelProfileData;
  id: string;
  flags: FlagModel[];
  values: MemberValueResponseModel[];
  variants: MemberVariantResponseModel[];
}
