/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Umbraco Management API
 * This shows all APIs available in this version of Umbraco - including all the legacy apis that are available for backward compatibility
 * OpenAPI spec version: Latest
 */
import type { MemberTypeCompositionModel } from './memberTypeCompositionModel.js';
import type { MemberTypeResponseModelDescription } from './memberTypeResponseModelDescription.js';
import type { MemberTypeResponseModelCollection } from './memberTypeResponseModelCollection.js';
import type { MemberTypePropertyTypeResponseModel } from './memberTypePropertyTypeResponseModel.js';
import type { MemberTypePropertyTypeContainerResponseModel } from './memberTypePropertyTypeContainerResponseModel.js';

export interface MemberTypeResponseModel {
  compositions: MemberTypeCompositionModel[];
  id: string;
  alias: string;
  name: string;
  description?: MemberTypeResponseModelDescription;
  icon: string;
  allowedAsRoot: boolean;
  variesByCulture: boolean;
  variesBySegment: boolean;
  collection?: MemberTypeResponseModelCollection;
  isElement: boolean;
  allowedInLibrary: boolean;
  properties: MemberTypePropertyTypeResponseModel[];
  containers: MemberTypePropertyTypeContainerResponseModel[];
}
