/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Umbraco Management API
 * This shows all APIs available in this version of Umbraco - including all the legacy apis that are available for backward compatibility
 * OpenAPI spec version: Latest
 */
import type { MemberVariantResponseModelCulture } from './memberVariantResponseModelCulture.js';
import type { MemberVariantResponseModelSegment } from './memberVariantResponseModelSegment.js';

export interface MemberVariantResponseModel {
  createDate: string;
  updateDate: string;
  culture?: MemberVariantResponseModelCulture;
  segment?: MemberVariantResponseModelSegment;
  name: string;
}
