/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Umbraco Management API
 * This shows all APIs available in this version of Umbraco - including all the legacy apis that are available for backward compatibility
 * OpenAPI spec version: Latest
 */
import type { ModelsBuilderResponseModelLastError } from './modelsBuilderResponseModelLastError.js';
import type { ModelsBuilderResponseModelVersion } from './modelsBuilderResponseModelVersion.js';
import type { ModelsBuilderResponseModelModelsNamespace } from './modelsBuilderResponseModelModelsNamespace.js';

export interface ModelsBuilderResponseModel {
  mode: string;
  canGenerate: boolean;
  outOfDateModels: boolean;
  lastError?: ModelsBuilderResponseModelLastError;
  version?: ModelsBuilderResponseModelVersion;
  modelsNamespace?: ModelsBuilderResponseModelModelsNamespace;
  trackingOutOfDateModels: boolean;
}
