/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Umbraco Management API
 * This shows all APIs available in this version of Umbraco - including all the legacy apis that are available for backward compatibility
 * OpenAPI spec version: Latest
 */
import type { NewsDashboardItemResponseModelBody } from './newsDashboardItemResponseModelBody.js';
import type { NewsDashboardItemResponseModelButtonText } from './newsDashboardItemResponseModelButtonText.js';
import type { NewsDashboardItemResponseModelImageUrl } from './newsDashboardItemResponseModelImageUrl.js';
import type { NewsDashboardItemResponseModelImageAltText } from './newsDashboardItemResponseModelImageAltText.js';
import type { NewsDashboardItemResponseModelUrl } from './newsDashboardItemResponseModelUrl.js';

export interface NewsDashboardItemResponseModel {
  priority: string;
  header: string;
  body?: NewsDashboardItemResponseModelBody;
  buttonText?: NewsDashboardItemResponseModelButtonText;
  imageUrl?: NewsDashboardItemResponseModelImageUrl;
  imageAltText?: NewsDashboardItemResponseModelImageAltText;
  url?: NewsDashboardItemResponseModelUrl;
}
