/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Umbraco Management API
 * This shows all APIs available in this version of Umbraco - including all the legacy apis that are available for backward compatibility
 * OpenAPI spec version: Latest
 */
import type { ProblemDetailsType } from './problemDetailsType.js';
import type { ProblemDetailsTitle } from './problemDetailsTitle.js';
import type { ProblemDetailsStatus } from './problemDetailsStatus.js';
import type { ProblemDetailsDetail } from './problemDetailsDetail.js';
import type { ProblemDetailsInstance } from './problemDetailsInstance.js';

export interface ProblemDetails {
  type?: ProblemDetailsType;
  title?: ProblemDetailsTitle;
  status?: ProblemDetailsStatus;
  detail?: ProblemDetailsDetail;
  instance?: ProblemDetailsInstance;
}
