/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Umbraco Management API
 * This shows all APIs available in this version of Umbraco - including all the legacy apis that are available for backward compatibility
 * OpenAPI spec version: Latest
 */
import type { PropertyTypeValidationModelMandatoryMessage } from './propertyTypeValidationModelMandatoryMessage.js';
import type { PropertyTypeValidationModelRegEx } from './propertyTypeValidationModelRegEx.js';
import type { PropertyTypeValidationModelRegExMessage } from './propertyTypeValidationModelRegExMessage.js';

export interface PropertyTypeValidationModel {
  mandatory: boolean;
  mandatoryMessage?: PropertyTypeValidationModelMandatoryMessage;
  regEx?: PropertyTypeValidationModelRegEx;
  regExMessage?: PropertyTypeValidationModelRegExMessage;
}
