/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Umbraco Management API
 * This shows all APIs available in this version of Umbraco - including all the legacy apis that are available for backward compatibility
 * OpenAPI spec version: Latest
 */

export type PublishableVariantStateModel = typeof PublishableVariantStateModel[keyof typeof PublishableVariantStateModel];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const PublishableVariantStateModel = {
  NotCreated: 'NotCreated',
  Draft: 'Draft',
  Published: 'Published',
  PublishedPendingChanges: 'PublishedPendingChanges',
  Trashed: 'Trashed',
} as const;
