/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Umbraco Management API
 * This shows all APIs available in this version of Umbraco - including all the legacy apis that are available for backward compatibility
 * OpenAPI spec version: Latest
 */
import type { RelationTypeResponseModelAlias } from './relationTypeResponseModelAlias.js';
import type { RelationTypeResponseModelParentObject } from './relationTypeResponseModelParentObject.js';
import type { RelationTypeResponseModelChildObject } from './relationTypeResponseModelChildObject.js';

export interface RelationTypeResponseModel {
  id: string;
  alias?: RelationTypeResponseModelAlias;
  parentObject?: RelationTypeResponseModelParentObject;
  childObject?: RelationTypeResponseModelChildObject;
  name: string;
  isBidirectional: boolean;
  isDependency: boolean;
}
