/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Umbraco Management API
 * This shows all APIs available in this version of Umbraco - including all the legacy apis that are available for backward compatibility
 * OpenAPI spec version: Latest
 */
import type { ReferenceByIdModel } from './referenceByIdModel.js';
import type { RelationReferenceModel } from './relationReferenceModel.js';
import type { RelationResponseModelComment } from './relationResponseModelComment.js';

export interface RelationResponseModel {
  id: string;
  relationType: ReferenceByIdModel;
  parent: RelationReferenceModel;
  child: RelationReferenceModel;
  createDate: string;
  comment?: RelationResponseModelComment;
}
