/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Umbraco Management API
 * This shows all APIs available in this version of Umbraco - including all the legacy apis that are available for backward compatibility
 * OpenAPI spec version: Latest
 */
import type { TagResponseModelText } from './tagResponseModelText.js';
import type { TagResponseModelGroup } from './tagResponseModelGroup.js';

export interface TagResponseModel {
  id: string;
  text?: TagResponseModelText;
  group?: TagResponseModelGroup;
  nodeCount: number;
}
