/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Umbraco Management API
 * This shows all APIs available in this version of Umbraco - including all the legacy apis that are available for backward compatibility
 * OpenAPI spec version: Latest
 */
import type { TemplateQueryExecuteModelRootDocument } from './templateQueryExecuteModelRootDocument.js';
import type { TemplateQueryExecuteModelDocumentTypeAlias } from './templateQueryExecuteModelDocumentTypeAlias.js';
import type { TemplateQueryExecuteModelFilters } from './templateQueryExecuteModelFilters.js';
import type { TemplateQueryExecuteModelSort } from './templateQueryExecuteModelSort.js';

export interface TemplateQueryExecuteModel {
  rootDocument?: TemplateQueryExecuteModelRootDocument;
  documentTypeAlias?: TemplateQueryExecuteModelDocumentTypeAlias;
  filters?: TemplateQueryExecuteModelFilters;
  sort?: TemplateQueryExecuteModelSort;
  take: number;
}
