/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Umbraco Management API
 * This shows all APIs available in this version of Umbraco - including all the legacy apis that are available for backward compatibility
 * OpenAPI spec version: Latest
 */
import type { TemplateResponseModelLayoutTemplate } from './templateResponseModelLayoutTemplate.js';
import type { TemplateResponseModelMasterTemplate } from './templateResponseModelMasterTemplate.js';
import type { TemplateResponseModelContent } from './templateResponseModelContent.js';

export interface TemplateResponseModel {
  id: string;
  layoutTemplate?: TemplateResponseModelLayoutTemplate;
  masterTemplate?: TemplateResponseModelMasterTemplate;
  name: string;
  alias: string;
  content?: TemplateResponseModelContent;
}
