/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Umbraco Management API
 * This shows all APIs available in this version of Umbraco - including all the legacy apis that are available for backward compatibility
 * OpenAPI spec version: Latest
 */
import type { TrackedReferenceMediaTypeModelIcon } from './trackedReferenceMediaTypeModelIcon.js';
import type { TrackedReferenceMediaTypeModelAlias } from './trackedReferenceMediaTypeModelAlias.js';
import type { TrackedReferenceMediaTypeModelName } from './trackedReferenceMediaTypeModelName.js';

export interface TrackedReferenceMediaTypeModel {
  id: string;
  icon?: TrackedReferenceMediaTypeModelIcon;
  alias?: TrackedReferenceMediaTypeModelAlias;
  name?: TrackedReferenceMediaTypeModelName;
}
