/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Umbraco Management API
 * This shows all APIs available in this version of Umbraco - including all the legacy apis that are available for backward compatibility
 * OpenAPI spec version: Latest
 */
import type { TrackedReferenceMemberTypeModelIcon } from './trackedReferenceMemberTypeModelIcon.js';
import type { TrackedReferenceMemberTypeModelAlias } from './trackedReferenceMemberTypeModelAlias.js';
import type { TrackedReferenceMemberTypeModelName } from './trackedReferenceMemberTypeModelName.js';

export interface TrackedReferenceMemberTypeModel {
  id: string;
  icon?: TrackedReferenceMemberTypeModelIcon;
  alias?: TrackedReferenceMemberTypeModelAlias;
  name?: TrackedReferenceMemberTypeModelName;
}
