/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Umbraco Management API
 * This shows all APIs available in this version of Umbraco - including all the legacy apis that are available for backward compatibility
 * OpenAPI spec version: Latest
 */
import type { MemberTypePropertyTypeVisibilityModel } from './memberTypePropertyTypeVisibilityModel.js';
import type { UpdateMemberTypePropertyTypeRequestModelContainer } from './updateMemberTypePropertyTypeRequestModelContainer.js';
import type { UpdateMemberTypePropertyTypeRequestModelDescription } from './updateMemberTypePropertyTypeRequestModelDescription.js';
import type { ReferenceByIdModel } from './referenceByIdModel.js';
import type { PropertyTypeValidationModel } from './propertyTypeValidationModel.js';
import type { PropertyTypeAppearanceModel } from './propertyTypeAppearanceModel.js';

export interface UpdateMemberTypePropertyTypeRequestModel {
  isSensitive: boolean;
  visibility: MemberTypePropertyTypeVisibilityModel;
  id: string;
  container?: UpdateMemberTypePropertyTypeRequestModelContainer;
  sortOrder: number;
  alias: string;
  name: string;
  description?: UpdateMemberTypePropertyTypeRequestModelDescription;
  dataType: ReferenceByIdModel;
  variesByCulture: boolean;
  variesBySegment: boolean;
  validation: PropertyTypeValidationModel;
  appearance: PropertyTypeAppearanceModel;
}
