/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Umbraco Management API
 * This shows all APIs available in this version of Umbraco - including all the legacy apis that are available for backward compatibility
 * OpenAPI spec version: Latest
 */
import type { UpdateWebhookRequestModelName } from './updateWebhookRequestModelName.js';
import type { UpdateWebhookRequestModelDescription } from './updateWebhookRequestModelDescription.js';
import type { UpdateWebhookRequestModelHeaders } from './updateWebhookRequestModelHeaders.js';

export interface UpdateWebhookRequestModel {
  events: string[];
  enabled: boolean;
  name?: UpdateWebhookRequestModelName;
  description?: UpdateWebhookRequestModelDescription;
  url: string;
  contentTypeKeys: string[];
  headers: UpdateWebhookRequestModelHeaders;
}
