/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Umbraco Management API
 * This shows all APIs available in this version of Umbraco - including all the legacy apis that are available for backward compatibility
 * OpenAPI spec version: Latest
 */
import type { MediaTypeSortModel } from './mediaTypeSortModel.js';
import type { MediaTypeCompositionModel } from './mediaTypeCompositionModel.js';
import type { UpdateMediaTypeRequestModelDescription } from './updateMediaTypeRequestModelDescription.js';
import type { UpdateMediaTypeRequestModelCollection } from './updateMediaTypeRequestModelCollection.js';
import type { UpdateMediaTypePropertyTypeRequestModel } from './updateMediaTypePropertyTypeRequestModel.js';
import type { UpdateMediaTypePropertyTypeContainerRequestModel } from './updateMediaTypePropertyTypeContainerRequestModel.js';

export interface UpdateMediaTypeRequestModel {
  allowedMediaTypes: MediaTypeSortModel[];
  compositions: MediaTypeCompositionModel[];
  alias: string;
  name: string;
  description?: UpdateMediaTypeRequestModelDescription;
  icon: string;
  allowedAsRoot: boolean;
  variesByCulture: boolean;
  variesBySegment: boolean;
  collection?: UpdateMediaTypeRequestModelCollection;
  isElement: boolean;
  allowedInLibrary: boolean;
  properties: UpdateMediaTypePropertyTypeRequestModel[];
  containers: UpdateMediaTypePropertyTypeContainerRequestModel[];
}
