/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Umbraco Management API
 * This shows all APIs available in this version of Umbraco - including all the legacy apis that are available for backward compatibility
 * OpenAPI spec version: Latest
 */
import type { UpdateMemberRequestModelOldPassword } from './updateMemberRequestModelOldPassword.js';
import type { UpdateMemberRequestModelNewPassword } from './updateMemberRequestModelNewPassword.js';
import type { UpdateMemberRequestModelGroups } from './updateMemberRequestModelGroups.js';
import type { MemberValueModel } from './memberValueModel.js';
import type { MemberVariantRequestModel } from './memberVariantRequestModel.js';

export interface UpdateMemberRequestModel {
  email: string;
  username: string;
  oldPassword?: UpdateMemberRequestModelOldPassword;
  newPassword?: UpdateMemberRequestModelNewPassword;
  groups?: UpdateMemberRequestModelGroups;
  isApproved: boolean;
  isLockedOut: boolean;
  isTwoFactorEnabled: boolean;
  values: MemberValueModel[];
  variants: MemberVariantRequestModel[];
}
