/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Umbraco Management API
 * This shows all APIs available in this version of Umbraco - including all the legacy apis that are available for backward compatibility
 * OpenAPI spec version: Latest
 */
import type { UpdateUserGroupRequestModelDescription } from './updateUserGroupRequestModelDescription.js';
import type { UpdateUserGroupRequestModelIcon } from './updateUserGroupRequestModelIcon.js';
import type { UpdateUserGroupRequestModelDocumentStartNode } from './updateUserGroupRequestModelDocumentStartNode.js';
import type { UpdateUserGroupRequestModelMediaStartNode } from './updateUserGroupRequestModelMediaStartNode.js';
import type { UpdateUserGroupRequestModelElementStartNode } from './updateUserGroupRequestModelElementStartNode.js';
import type { IPermissionPresentationModel } from './iPermissionPresentationModel.js';

export interface UpdateUserGroupRequestModel {
  name: string;
  alias: string;
  description?: UpdateUserGroupRequestModelDescription;
  icon?: UpdateUserGroupRequestModelIcon;
  sections: string[];
  languages: string[];
  hasAccessToAllLanguages: boolean;
  documentStartNode?: UpdateUserGroupRequestModelDocumentStartNode;
  documentRootAccess: boolean;
  mediaStartNode?: UpdateUserGroupRequestModelMediaStartNode;
  mediaRootAccess: boolean;
  elementStartNode?: UpdateUserGroupRequestModelElementStartNode;
  elementRootAccess: boolean;
  fallbackPermissions: string[];
  permissions: IPermissionPresentationModel[];
}
