/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Umbraco Management API
 * This shows all APIs available in this version of Umbraco - including all the legacy apis that are available for backward compatibility
 * OpenAPI spec version: Latest
 */
import type { UpdateDocumentTypePropertyTypeRequestModelContainer } from './updateDocumentTypePropertyTypeRequestModelContainer.js';
import type { UpdateDocumentTypePropertyTypeRequestModelDescription } from './updateDocumentTypePropertyTypeRequestModelDescription.js';
import type { ReferenceByIdModel } from './referenceByIdModel.js';
import type { PropertyTypeValidationModel } from './propertyTypeValidationModel.js';
import type { PropertyTypeAppearanceModel } from './propertyTypeAppearanceModel.js';

export interface UpdateDocumentTypePropertyTypeRequestModel {
  id: string;
  container?: UpdateDocumentTypePropertyTypeRequestModelContainer;
  sortOrder: number;
  alias: string;
  name: string;
  description?: UpdateDocumentTypePropertyTypeRequestModelDescription;
  dataType: ReferenceByIdModel;
  variesByCulture: boolean;
  variesBySegment: boolean;
  validation: PropertyTypeValidationModel;
  appearance: PropertyTypeAppearanceModel;
}
