/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Umbraco Management API
 * This shows all APIs available in this version of Umbraco - including all the legacy apis that are available for backward compatibility
 * OpenAPI spec version: Latest
 */
import type { ReferenceByIdModel } from './referenceByIdModel.js';
import type { UpdateDocumentTypeRequestModelDefaultTemplate } from './updateDocumentTypeRequestModelDefaultTemplate.js';
import type { DocumentTypeCleanupModel } from './documentTypeCleanupModel.js';
import type { DocumentTypeSortModel } from './documentTypeSortModel.js';
import type { DocumentTypeCompositionModel } from './documentTypeCompositionModel.js';
import type { UpdateDocumentTypeRequestModelDescription } from './updateDocumentTypeRequestModelDescription.js';
import type { UpdateDocumentTypeRequestModelCollection } from './updateDocumentTypeRequestModelCollection.js';
import type { UpdateDocumentTypePropertyTypeRequestModel } from './updateDocumentTypePropertyTypeRequestModel.js';
import type { UpdateDocumentTypePropertyTypeContainerRequestModel } from './updateDocumentTypePropertyTypeContainerRequestModel.js';

export interface UpdateDocumentTypeRequestModel {
  allowedTemplates: ReferenceByIdModel[];
  defaultTemplate?: UpdateDocumentTypeRequestModelDefaultTemplate;
  cleanup: DocumentTypeCleanupModel;
  allowedDocumentTypes: DocumentTypeSortModel[];
  compositions: DocumentTypeCompositionModel[];
  alias: string;
  name: string;
  description?: UpdateDocumentTypeRequestModelDescription;
  icon: string;
  allowedAsRoot: boolean;
  variesByCulture: boolean;
  variesBySegment: boolean;
  collection?: UpdateDocumentTypeRequestModelCollection;
  isElement: boolean;
  allowedInLibrary: boolean;
  properties: UpdateDocumentTypePropertyTypeRequestModel[];
  containers: UpdateDocumentTypePropertyTypeContainerRequestModel[];
}
