/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Umbraco Management API
 * This shows all APIs available in this version of Umbraco - including all the legacy apis that are available for backward compatibility
 * OpenAPI spec version: Latest
 */
import type { UpdateMediaTypePropertyTypeContainerRequestModelParent } from './updateMediaTypePropertyTypeContainerRequestModelParent.js';
import type { UpdateMediaTypePropertyTypeContainerRequestModelName } from './updateMediaTypePropertyTypeContainerRequestModelName.js';

export interface UpdateMediaTypePropertyTypeContainerRequestModel {
  id: string;
  parent?: UpdateMediaTypePropertyTypeContainerRequestModelParent;
  name?: UpdateMediaTypePropertyTypeContainerRequestModelName;
  type: string;
  sortOrder: number;
}
