/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Umbraco Management API
 * This shows all APIs available in this version of Umbraco - including all the legacy apis that are available for backward compatibility
 * OpenAPI spec version: Latest
 */
import type { MemberTypeCompositionModel } from './memberTypeCompositionModel.js';
import type { UpdateMemberTypeRequestModelDescription } from './updateMemberTypeRequestModelDescription.js';
import type { UpdateMemberTypeRequestModelCollection } from './updateMemberTypeRequestModelCollection.js';
import type { UpdateMemberTypePropertyTypeRequestModel } from './updateMemberTypePropertyTypeRequestModel.js';
import type { UpdateMemberTypePropertyTypeContainerRequestModel } from './updateMemberTypePropertyTypeContainerRequestModel.js';

export interface UpdateMemberTypeRequestModel {
  compositions: MemberTypeCompositionModel[];
  alias: string;
  name: string;
  description?: UpdateMemberTypeRequestModelDescription;
  icon: string;
  allowedAsRoot: boolean;
  variesByCulture: boolean;
  variesBySegment: boolean;
  collection?: UpdateMemberTypeRequestModelCollection;
  isElement: boolean;
  allowedInLibrary: boolean;
  properties: UpdateMemberTypePropertyTypeRequestModel[];
  containers: UpdateMemberTypePropertyTypeContainerRequestModel[];
}
