/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Umbraco Management API
 * This shows all APIs available in this version of Umbraco - including all the legacy apis that are available for backward compatibility
 * OpenAPI spec version: Latest
 */

export interface UserInstallRequestModel {
  /**
   * @minLength 0
   * @maxLength 255
   */
  name: string;
  /** @minLength 1 */
  email: string;
  /** @minLength 1 */
  password: string;
  subscribeToNewsletter: boolean;
}
