/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Umbraco Management API
 * This shows all APIs available in this version of Umbraco - including all the legacy apis that are available for backward compatibility
 * OpenAPI spec version: Latest
 */
import type { UserGroupItemResponseModelIcon } from './userGroupItemResponseModelIcon.js';
import type { UserGroupItemResponseModelAlias } from './userGroupItemResponseModelAlias.js';
import type { FlagModel } from './flagModel.js';

export interface UserGroupItemResponseModel {
  icon?: UserGroupItemResponseModelIcon;
  alias?: UserGroupItemResponseModelAlias;
  name: string;
  id: string;
  flags: FlagModel[];
}
