/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Umbraco Management API
 * This shows all APIs available in this version of Umbraco - including all the legacy apis that are available for backward compatibility
 * OpenAPI spec version: Latest
 */
import type { UserResponseModelLanguageIsoCode } from './userResponseModelLanguageIsoCode.js';
import type { ReferenceByIdModel } from './referenceByIdModel.js';
import type { UserStateModel } from './userStateModel.js';
import type { UserResponseModelLastLoginDate } from './userResponseModelLastLoginDate.js';
import type { UserResponseModelLastLockoutDate } from './userResponseModelLastLockoutDate.js';
import type { UserResponseModelLastPasswordChangeDate } from './userResponseModelLastPasswordChangeDate.js';
import type { UserKindModel } from './userKindModel.js';

export interface UserResponseModel {
  id: string;
  languageIsoCode?: UserResponseModelLanguageIsoCode;
  documentStartNodeIds: ReferenceByIdModel[];
  hasDocumentRootAccess: boolean;
  mediaStartNodeIds: ReferenceByIdModel[];
  hasMediaRootAccess: boolean;
  elementStartNodeIds: ReferenceByIdModel[];
  hasElementRootAccess: boolean;
  avatarUrls: string[];
  state: UserStateModel;
  failedLoginAttempts: number;
  createDate: string;
  updateDate: string;
  lastLoginDate?: UserResponseModelLastLoginDate;
  lastLockoutDate?: UserResponseModelLastLockoutDate;
  lastPasswordChangeDate?: UserResponseModelLastPasswordChangeDate;
  isAdmin: boolean;
  kind: UserKindModel;
  email: string;
  userName: string;
  name: string;
  userGroupIds: ReferenceByIdModel[];
}
