/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Umbraco Management API
 * This shows all APIs available in this version of Umbraco - including all the legacy apis that are available for backward compatibility
 * OpenAPI spec version: Latest
 */
import type { UserKindModel } from './userKindModel.js';
import type { FlagModel } from './flagModel.js';

export interface UserItemResponseModel {
  avatarUrls: string[];
  kind: UserKindModel;
  name: string;
  id: string;
  flags: FlagModel[];
}
