/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Umbraco Management API
 * This shows all APIs available in this version of Umbraco - including all the legacy apis that are available for backward compatibility
 * OpenAPI spec version: Latest
 */
import type { WebhookEventResponseModel } from './webhookEventResponseModel.js';
import type { WebhookResponseModelName } from './webhookResponseModelName.js';
import type { WebhookResponseModelDescription } from './webhookResponseModelDescription.js';
import type { WebhookResponseModelHeaders } from './webhookResponseModelHeaders.js';

export interface WebhookResponseModel {
  id: string;
  events: WebhookEventResponseModel[];
  enabled: boolean;
  name?: WebhookResponseModelName;
  description?: WebhookResponseModelDescription;
  url: string;
  contentTypeKeys: string[];
  headers: WebhookResponseModelHeaders;
}
