/**
 * Generated by orval v8.20.0 🍺
 * Do not edit manually.
 * Umbraco Management API
 * This shows all APIs available in this version of Umbraco - including all the legacy apis that are available for backward compatibility
 * OpenAPI spec version: Latest
 */

export type ContentSortFieldModel = typeof ContentSortFieldModel[keyof typeof ContentSortFieldModel];


export const ContentSortFieldModel = {
  Name: 'Name',
  CreateDate: 'CreateDate',
  UpdateDate: 'UpdateDate',
} as const;
