/**
 * Generated by orval v8.20.0 🍺
 * Do not edit manually.
 * Umbraco Management API
 * This shows all APIs available in this version of Umbraco - including all the legacy apis that are available for backward compatibility
 * OpenAPI spec version: Latest
 */
import type { ElementValueModel } from './elementValueModel.js';
import type { ElementVariantRequestModel } from './elementVariantRequestModel.js';
import type { ReferenceByIdModel } from './referenceByIdModel.js';

export interface CreateAndPublishElementRequestModel {
  culturesToPublish: string[];
  documentType: ReferenceByIdModel;
  parent?: null | ReferenceByIdModel;
  /** @nullable */
  id?: string | null;
  values: ElementValueModel[];
  variants: ElementVariantRequestModel[];
}
