/**
 * Generated by orval v8.20.0 🍺
 * Do not edit manually.
 * Umbraco Management API
 * This shows all APIs available in this version of Umbraco - including all the legacy apis that are available for backward compatibility
 * OpenAPI spec version: Latest
 */
import type { CreateMemberTypePropertyTypeContainerRequestModel } from './createMemberTypePropertyTypeContainerRequestModel.js';
import type { CreateMemberTypePropertyTypeRequestModel } from './createMemberTypePropertyTypeRequestModel.js';
import type { MemberTypeCompositionModel } from './memberTypeCompositionModel.js';
import type { ReferenceByIdModel } from './referenceByIdModel.js';

export interface CreateMemberTypeRequestModel {
  compositions: MemberTypeCompositionModel[];
  parent?: null | ReferenceByIdModel;
  /** @nullable */
  id?: string | null;
  alias: string;
  name: string;
  /** @nullable */
  description?: string | null;
  icon: string;
  allowedAsRoot: boolean;
  variesByCulture: boolean;
  variesBySegment: boolean;
  collection?: null | ReferenceByIdModel;
  isElement: boolean;
  allowedInLibrary: boolean;
  properties: CreateMemberTypePropertyTypeRequestModel[];
  containers: CreateMemberTypePropertyTypeContainerRequestModel[];
}
