/**
 * Generated by orval v8.20.0 🍺
 * Do not edit manually.
 * Umbraco Management API
 * This shows all APIs available in this version of Umbraco - including all the legacy apis that are available for backward compatibility
 * OpenAPI spec version: Latest
 */
import type { MemberTypePropertyTypeVisibilityModel } from './memberTypePropertyTypeVisibilityModel.js';
import type { PropertyTypeAppearanceModel } from './propertyTypeAppearanceModel.js';
import type { PropertyTypeValidationModel } from './propertyTypeValidationModel.js';
import type { ReferenceByIdModel } from './referenceByIdModel.js';

export interface CreateMemberTypePropertyTypeRequestModel {
  isSensitive: boolean;
  visibility: MemberTypePropertyTypeVisibilityModel;
  id: string;
  container?: null | ReferenceByIdModel;
  sortOrder: number;
  alias: string;
  name: string;
  /** @nullable */
  description?: string | null;
  dataType: ReferenceByIdModel;
  variesByCulture: boolean;
  variesBySegment: boolean;
  validation: PropertyTypeValidationModel;
  appearance: PropertyTypeAppearanceModel;
}
