/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Umbraco Management API
 * This shows all APIs available in this version of Umbraco - including all the legacy apis that are available for backward compatibility
 * OpenAPI spec version: Latest
 */
import type { DictionaryItemTranslationModel } from './dictionaryItemTranslationModel.js';
import type { ReferenceByIdModel } from './referenceByIdModel.js';

export interface CreateDictionaryItemRequestModel {
  /** @minLength 1 */
  name: string;
  translations: DictionaryItemTranslationModel[];
  /** @nullable */
  id?: string | null;
  parent?: ReferenceByIdModel | null;
}
