/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Umbraco Management API
 * This shows all APIs available in this version of Umbraco - including all the legacy apis that are available for backward compatibility
 * OpenAPI spec version: Latest
 */

export interface CreateDocumentTypeTemplateRequestModel {
  /** @minLength 1 */
  alias: string;
  /** @minLength 1 */
  name: string;
  isDefault: boolean;
}
