/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Umbraco Management API
 * This shows all APIs available in this version of Umbraco - including all the legacy apis that are available for backward compatibility
 * OpenAPI spec version: Latest
 */
import type { DocumentValueModel } from './documentValueModel.js';
import type { DocumentVariantRequestModel } from './documentVariantRequestModel.js';
import type { CreateAndPublishDocumentRequestModelParent } from './createAndPublishDocumentRequestModelParent.js';
import type { ReferenceByIdModel } from './referenceByIdModel.js';
import type { CreateAndPublishDocumentRequestModelTemplate } from './createAndPublishDocumentRequestModelTemplate.js';

export interface CreateAndPublishDocumentRequestModel {
  values: DocumentValueModel[];
  variants: DocumentVariantRequestModel[];
  /** @nullable */
  id?: string | null;
  /** @nullable */
  parent?: CreateAndPublishDocumentRequestModelParent;
  documentType: ReferenceByIdModel;
  /** @nullable */
  template: CreateAndPublishDocumentRequestModelTemplate;
  culturesToPublish: string[];
}
