/**
 * Generated by orval v8.20.0 🍺
 * Do not edit manually.
 * Umbraco Management API
 * This shows all APIs available in this version of Umbraco - including all the legacy apis that are available for backward compatibility
 * OpenAPI spec version: Latest
 */
import type { JsonObject } from './jsonObject.js';

export interface DataTypeSchemaItemResponseModel {
  id: string;
  /** @nullable */
  valueTypeName?: string | null;
  jsonSchema?: null | JsonObject;
  /** @nullable */
  error?: string | null;
}
