/**
 * Generated by orval v8.20.0 🍺
 * Do not edit manually.
 * Umbraco Management API
 * This shows all APIs available in this version of Umbraco - including all the legacy apis that are available for backward compatibility
 * OpenAPI spec version: Latest
 */
import type { FlagModel } from './flagModel.js';

export interface DataTypeItemResponseModel {
  /** @nullable */
  editorUiAlias?: string | null;
  editorAlias: string;
  isDeletable: boolean;
  name: string;
  id: string;
  flags: FlagModel[];
}
