/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Umbraco Management API
 * This shows all APIs available in this version of Umbraco - including all the legacy apis that are available for backward compatibility
 * OpenAPI spec version: Latest
 */
import type { DocumentTypeReferenceResponseModel } from './documentTypeReferenceResponseModel.js';
import type { DocumentVariantItemResponseModel } from './documentVariantItemResponseModel.js';
import type { FlagModel } from './flagModel.js';
import type { ReferenceByIdModel } from './referenceByIdModel.js';

export interface DocumentTreeItemResponseModel {
  hasChildren: boolean;
  id: string;
  parent?: ReferenceByIdModel | null;
  flags: FlagModel[];
  noAccess: boolean;
  isTrashed: boolean;
  createDate: string;
  isProtected: boolean;
  ancestors: ReferenceByIdModel[];
  documentType: DocumentTypeReferenceResponseModel;
  variants: DocumentVariantItemResponseModel[];
}
