/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Umbraco Management API
 * This shows all APIs available in this version of Umbraco - including all the legacy apis that are available for backward compatibility
 * OpenAPI spec version: Latest
 */

export interface DocumentConfigurationResponseModel {
  disableDeleteWhenReferenced: boolean;
  disableUnpublishWhenReferenced: boolean;
  allowEditInvariantFromNonDefault: boolean;
  /** @deprecated */
  allowNonExistingSegmentsCreation: boolean;
}
