/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Umbraco Management API
 * This shows all APIs available in this version of Umbraco - including all the legacy apis that are available for backward compatibility
 * OpenAPI spec version: Latest
 */
import type { DocumentTypeReferenceResponseModel } from './documentTypeReferenceResponseModel.js';
import type { DocumentVariantItemResponseModel } from './documentVariantItemResponseModel.js';
import type { ItemReferenceByIdResponseModel } from './itemReferenceByIdResponseModel.js';

export interface DocumentRecycleBinItemResponseModel {
  id: string;
  createDate: string;
  hasChildren: boolean;
  parent?: ItemReferenceByIdResponseModel | null;
  documentType: DocumentTypeReferenceResponseModel;
  variants: DocumentVariantItemResponseModel[];
}
