/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Umbraco Management API
 * This shows all APIs available in this version of Umbraco - including all the legacy apis that are available for backward compatibility
 * OpenAPI spec version: Latest
 */

export interface DocumentValueResponseModel {
  /** @nullable */
  culture?: string | null;
  /** @nullable */
  segment?: string | null;
  /** @minLength 1 */
  alias: string;
  value?: unknown | null;
  /** @minLength 1 */
  editorAlias: string;
}
