/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Umbraco Management API
 * This shows all APIs available in this version of Umbraco - including all the legacy apis that are available for backward compatibility
 * OpenAPI spec version: Latest
 */
import type { DynamicRootContextRequestModel } from './dynamicRootContextRequestModel.js';
import type { DynamicRootQueryRequestModel } from './dynamicRootQueryRequestModel.js';

export interface DynamicRootRequestModel {
  context: DynamicRootContextRequestModel;
  query: DynamicRootQueryRequestModel;
}
