/**
 * Generated by orval v8.20.0 🍺
 * Do not edit manually.
 * Umbraco Management API
 * This shows all APIs available in this version of Umbraco - including all the legacy apis that are available for backward compatibility
 * OpenAPI spec version: Latest
 */
import type { DocumentTypeReferenceResponseModel } from './documentTypeReferenceResponseModel.js';
import type { ElementVariantItemResponseModel } from './elementVariantItemResponseModel.js';
import type { ItemReferenceByIdResponseModel } from './itemReferenceByIdResponseModel.js';

export interface ElementRecycleBinItemResponseModel {
  documentType?: null | DocumentTypeReferenceResponseModel;
  variants: ElementVariantItemResponseModel[];
  isFolder: boolean;
  name: string;
  id: string;
  createDate: string;
  hasChildren: boolean;
  parent?: null | ItemReferenceByIdResponseModel;
}
