/**
 * Generated by orval v8.20.0 🍺
 * Do not edit manually.
 * Umbraco Management API
 * This shows all APIs available in this version of Umbraco - including all the legacy apis that are available for backward compatibility
 * OpenAPI spec version: Latest
 */
import type { FlagModel } from './flagModel.js';
import type { PublishableVariantStateModel } from './publishableVariantStateModel.js';

export interface ElementVariantResponseModel {
  id: string;
  flags: FlagModel[];
  state: PublishableVariantStateModel;
  /** @nullable */
  publishDate?: string | null;
  /** @nullable */
  scheduledPublishDate?: string | null;
  /** @nullable */
  scheduledUnpublishDate?: string | null;
  createDate: string;
  updateDate: string;
  /** @nullable */
  culture?: string | null;
  /** @nullable */
  segment?: string | null;
  name: string;
}
