/**
 * Generated by orval v8.20.0 🍺
 * Do not edit manually.
 * Umbraco Management API
 * This shows all APIs available in this version of Umbraco - including all the legacy apis that are available for backward compatibility
 * OpenAPI spec version: Latest
 */
import type { HealthCheckActionRequestModelActionParameters } from './healthCheckActionRequestModelActionParameters.js';
import type { ReferenceByIdModel } from './referenceByIdModel.js';

export interface HealthCheckActionRequestModel {
  healthCheck: ReferenceByIdModel;
  /** @nullable */
  alias?: string | null;
  /** @nullable */
  name?: string | null;
  /** @nullable */
  description?: string | null;
  valueRequired: boolean;
  /** @nullable */
  providedValue?: string | null;
  /** @nullable */
  providedValueValidation?: string | null;
  /** @nullable */
  providedValueValidationRegex?: string | null;
  /** @nullable */
  actionParameters?: HealthCheckActionRequestModelActionParameters;
}
