/**
 * Generated by orval v8.17.0 🍺
 * Do not edit manually.
 * Umbraco Management API
 * This shows all APIs available in this version of Umbraco - including all the legacy apis that are available for backward compatibility
 * OpenAPI spec version: Latest
 */
import type { IPermissionPresentationModelUnknownTypePermissionPresentationModelType } from './iPermissionPresentationModelUnknownTypePermissionPresentationModelType.js';

export interface IPermissionPresentationModelUnknownTypePermissionPresentationModel {
  $type: IPermissionPresentationModelUnknownTypePermissionPresentationModelType;
  verbs: string[];
  context: string;
}
