/**
 * Generated by orval v8.20.0 🍺
 * Do not edit manually.
 * Umbraco Management API
 * This shows all APIs available in this version of Umbraco - including all the legacy apis that are available for backward compatibility
 * OpenAPI spec version: Latest
 */
import type { IReferenceResponseModelDocumentTypePropertyTypeReferenceResponseModelType } from './iReferenceResponseModelDocumentTypePropertyTypeReferenceResponseModelType.js';
import type { TrackedReferenceDocumentTypeModel } from './trackedReferenceDocumentTypeModel.js';

export interface IReferenceResponseModelDocumentTypePropertyTypeReferenceResponseModel {
  $type: IReferenceResponseModelDocumentTypePropertyTypeReferenceResponseModelType;
  documentType: TrackedReferenceDocumentTypeModel;
  /** @nullable */
  alias?: string | null;
  id: string;
  /** @nullable */
  name?: string | null;
}
