/**
 * Generated by orval v8.20.0 🍺
 * Do not edit manually.
 * Umbraco Management API
 * This shows all APIs available in this version of Umbraco - including all the legacy apis that are available for backward compatibility
 * OpenAPI spec version: Latest
 */
import type { ElementVariantItemResponseModel } from './elementVariantItemResponseModel.js';
import type { IReferenceResponseModelElementReferenceResponseModelType } from './iReferenceResponseModelElementReferenceResponseModelType.js';
import type { TrackedReferenceDocumentTypeModel } from './trackedReferenceDocumentTypeModel.js';

export interface IReferenceResponseModelElementReferenceResponseModel {
  $type: IReferenceResponseModelElementReferenceResponseModelType;
  /** @nullable */
  published?: boolean | null;
  documentType: TrackedReferenceDocumentTypeModel;
  variants: ElementVariantItemResponseModel[];
  id: string;
  /** @nullable */
  name?: string | null;
}
