/**
 * Generated by orval v8.17.0 🍺
 * Do not edit manually.
 * Umbraco Management API
 * This shows all APIs available in this version of Umbraco - including all the legacy apis that are available for backward compatibility
 * OpenAPI spec version: Latest
 */
import type { IReferenceResponseModelDefaultReferenceResponseModelType } from './iReferenceResponseModelDefaultReferenceResponseModelType.js';

export interface IReferenceResponseModelDefaultReferenceResponseModel {
  $type: IReferenceResponseModelDefaultReferenceResponseModelType;
  /** @nullable */
  type?: string | null;
  /** @nullable */
  icon?: string | null;
  id: string;
  /** @nullable */
  name?: string | null;
}
