/**
 * Generated by orval v8.20.0 🍺
 * Do not edit manually.
 * Umbraco Management API
 * This shows all APIs available in this version of Umbraco - including all the legacy apis that are available for backward compatibility
 * OpenAPI spec version: Latest
 */
import type { IReferenceResponseModelMemberTypePropertyTypeReferenceResponseModelType } from './iReferenceResponseModelMemberTypePropertyTypeReferenceResponseModelType.js';
import type { TrackedReferenceMemberTypeModel } from './trackedReferenceMemberTypeModel.js';

export interface IReferenceResponseModelMemberTypePropertyTypeReferenceResponseModel {
  $type: IReferenceResponseModelMemberTypePropertyTypeReferenceResponseModelType;
  memberType: TrackedReferenceMemberTypeModel;
  /** @nullable */
  alias?: string | null;
  id: string;
  /** @nullable */
  name?: string | null;
}
