/**
 * Generated by orval v8.20.0 🍺
 * Do not edit manually.
 * Umbraco Management API
 * This shows all APIs available in this version of Umbraco - including all the legacy apis that are available for backward compatibility
 * OpenAPI spec version: Latest
 */
import type { IReferenceResponseModelMemberReferenceResponseModelType } from './iReferenceResponseModelMemberReferenceResponseModelType.js';
import type { TrackedReferenceMemberTypeModel } from './trackedReferenceMemberTypeModel.js';

export interface IReferenceResponseModelMemberReferenceResponseModel {
  $type: IReferenceResponseModelMemberReferenceResponseModelType;
  memberType: TrackedReferenceMemberTypeModel;
  id: string;
  /** @nullable */
  name?: string | null;
}
