/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Umbraco Management API
 * This shows all APIs available in this version of Umbraco - including all the legacy apis that are available for backward compatibility
 * OpenAPI spec version: Latest
 */
import type { JsonNodeOptionsProperty } from './jsonNodeOptionsProperty.js';
import type { JsonNodeParent } from './jsonNodeParent.js';

export interface JsonNode {
  /** @nullable */
  readonly options?: JsonNodeOptionsProperty;
  /** @nullable */
  readonly parent?: JsonNodeParent;
  readonly root: JsonNode;
}
