/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Umbraco Management API
 * This shows all APIs available in this version of Umbraco - including all the legacy apis that are available for backward compatibility
 * OpenAPI spec version: Latest
 */
import type { FlagModel } from './flagModel.js';
import type { MediaTypeCollectionReferenceResponseModel } from './mediaTypeCollectionReferenceResponseModel.js';
import type { MediaValueResponseModel } from './mediaValueResponseModel.js';
import type { MediaVariantResponseModel } from './mediaVariantResponseModel.js';

export interface MediaCollectionResponseModel {
  values: MediaValueResponseModel[];
  variants: MediaVariantResponseModel[];
  id: string;
  flags: FlagModel[];
  /** @nullable */
  creator?: string | null;
  sortOrder: number;
  mediaType: MediaTypeCollectionReferenceResponseModel;
}
