/**
 * Generated by orval v8.20.0 🍺
 * Do not edit manually.
 * Umbraco Management API
 * This shows all APIs available in this version of Umbraco - including all the legacy apis that are available for backward compatibility
 * OpenAPI spec version: Latest
 */
import type { FlagModel } from './flagModel.js';
import type { MediaTypeReferenceResponseModel } from './mediaTypeReferenceResponseModel.js';
import type { ReferenceByIdModel } from './referenceByIdModel.js';
import type { VariantItemResponseModel } from './variantItemResponseModel.js';

export interface MediaItemResponseModel {
  isTrashed: boolean;
  parent?: null | ReferenceByIdModel;
  hasChildren: boolean;
  mediaType: MediaTypeReferenceResponseModel;
  variants: VariantItemResponseModel[];
  id: string;
  flags: FlagModel[];
}
