/**
 * Generated by orval v8.20.0 🍺
 * Do not edit manually.
 * Umbraco Management API
 * This shows all APIs available in this version of Umbraco - including all the legacy apis that are available for backward compatibility
 * OpenAPI spec version: Latest
 */

export type MemberKindModel = typeof MemberKindModel[keyof typeof MemberKindModel];


export const MemberKindModel = {
  Default: 'Default',
  Api: 'Api',
  ExternalOnly: 'ExternalOnly',
} as const;
