/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Umbraco Management API
 * This shows all APIs available in this version of Umbraco - including all the legacy apis that are available for backward compatibility
 * OpenAPI spec version: Latest
 */
import type { MemberTypeCompositionModel } from './memberTypeCompositionModel.js';
import type { MemberTypePropertyTypeContainerResponseModel } from './memberTypePropertyTypeContainerResponseModel.js';
import type { MemberTypePropertyTypeResponseModel } from './memberTypePropertyTypeResponseModel.js';
import type { ReferenceByIdModel } from './referenceByIdModel.js';

export interface MemberTypeResponseModel {
  /** @minLength 1 */
  alias: string;
  /** @minLength 1 */
  name: string;
  /** @nullable */
  description?: string | null;
  /** @minLength 1 */
  icon: string;
  allowedAsRoot: boolean;
  variesByCulture: boolean;
  variesBySegment: boolean;
  collection?: ReferenceByIdModel | null;
  isElement: boolean;
  properties: MemberTypePropertyTypeResponseModel[];
  containers: MemberTypePropertyTypeContainerResponseModel[];
  id: string;
  compositions: MemberTypeCompositionModel[];
}
