/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Umbraco Management API
 * This shows all APIs available in this version of Umbraco - including all the legacy apis that are available for backward compatibility
 * OpenAPI spec version: Latest
 */
import type { MemberReferenceResponseModelType } from './memberReferenceResponseModelType.js';
import type { TrackedReferenceMemberTypeModel } from './trackedReferenceMemberTypeModel.js';

export interface MemberReferenceResponseModel {
  $type: MemberReferenceResponseModelType;
  id: string;
  /** @nullable */
  name?: string | null;
  memberType: TrackedReferenceMemberTypeModel;
}
