/**
 * Generated by orval v8.17.0 🍺
 * Do not edit manually.
 * Umbraco Management API
 * This shows all APIs available in this version of Umbraco - including all the legacy apis that are available for backward compatibility
 * OpenAPI spec version: Latest
 */

export type OperatorModel = typeof OperatorModel[keyof typeof OperatorModel];


export const OperatorModel = {
  Equals: 'Equals',
  NotEquals: 'NotEquals',
  Contains: 'Contains',
  NotContains: 'NotContains',
  LessThan: 'LessThan',
  LessThanEqualTo: 'LessThanEqualTo',
  GreaterThan: 'GreaterThan',
  GreaterThanEqualTo: 'GreaterThanEqualTo',
} as const;
