/**
 * Generated by orval v8.20.0 🍺
 * Do not edit manually.
 * Umbraco Management API
 * This shows all APIs available in this version of Umbraco - including all the legacy apis that are available for backward compatibility
 * OpenAPI spec version: Latest
 */
import type { ElementItemResponseModel } from './elementItemResponseModel.js';

export interface PagedModelElementItemResponseModel {
  items: ElementItemResponseModel[];
  total: number;
}
