/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Umbraco Management API
 * This shows all APIs available in this version of Umbraco - including all the legacy apis that are available for backward compatibility
 * OpenAPI spec version: Latest
 */

export interface PatchOperationRequestModel {
  /** @minLength 1 */
  op: string;
  /** @minLength 1 */
  path: string;
  value?: unknown | null;
}
