/**
 * Generated by orval v8.20.0 🍺
 * Do not edit manually.
 * Umbraco Management API
 * This shows all APIs available in this version of Umbraco - including all the legacy apis that are available for backward compatibility
 * OpenAPI spec version: Latest
 */
import type { MemberGroupItemResponseModel } from './memberGroupItemResponseModel.js';
import type { MemberItemResponseModel } from './memberItemResponseModel.js';
import type { ReferenceByIdModel } from './referenceByIdModel.js';

export interface PublicAccessResponseModel {
  members: MemberItemResponseModel[];
  groups: MemberGroupItemResponseModel[];
  isProtectedByAncestor: boolean;
  loginDocument: ReferenceByIdModel;
  errorDocument: ReferenceByIdModel;
}
