/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Umbraco Management API
 * This shows all APIs available in this version of Umbraco - including all the legacy apis that are available for backward compatibility
 * OpenAPI spec version: Latest
 */
import type { DocumentTypeReferenceResponseModel } from './documentTypeReferenceResponseModel.js';
import type { DocumentValueResponseModel } from './documentValueResponseModel.js';
import type { DocumentVariantResponseModel } from './documentVariantResponseModel.js';
import type { FlagModel } from './flagModel.js';
import type { ReferenceByIdModel } from './referenceByIdModel.js';

export interface PublishedDocumentResponseModel {
  values: DocumentValueResponseModel[];
  variants: DocumentVariantResponseModel[];
  id: string;
  flags: FlagModel[];
  documentType: DocumentTypeReferenceResponseModel;
  template?: ReferenceByIdModel | null;
  isTrashed: boolean;
}
