/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Umbraco Management API
 * This shows all APIs available in this version of Umbraco - including all the legacy apis that are available for backward compatibility
 * OpenAPI spec version: Latest
 */
import type { ObjectTypeResponseModel } from './objectTypeResponseModel.js';

export interface RelationTypeResponseModel {
  /** @minLength 1 */
  name: string;
  isBidirectional: boolean;
  isDependency: boolean;
  id: string;
  /** @nullable */
  alias?: string | null;
  parentObject?: ObjectTypeResponseModel | null;
  childObject?: ObjectTypeResponseModel | null;
}
