/**
 * Generated by orval v8.20.0 🍺
 * Do not edit manually.
 * Umbraco Management API
 * This shows all APIs available in this version of Umbraco - including all the legacy apis that are available for backward compatibility
 * OpenAPI spec version: Latest
 */
import type { SignalRClientSettingsResponseModel } from './signalRClientSettingsResponseModel.js';

export interface ServerConfigurationResponseModel {
  allowPasswordReset: boolean;
  versionCheckPeriod: number;
  allowLocalLogin: boolean;
  umbracoCssPath: string;
  signalR: SignalRClientSettingsResponseModel;
}
