/**
 * Generated by orval v8.20.0 🍺
 * Do not edit manually.
 * Umbraco Management API
 * This shows all APIs available in this version of Umbraco - including all the legacy apis that are available for backward compatibility
 * OpenAPI spec version: Latest
 */
import type { ContentSortFieldModel } from './contentSortFieldModel.js';
import type { DirectionModel } from './directionModel.js';

export interface SortDocumentChildrenByFieldRequestModel {
  /** @nullable */
  culture?: string | null;
  field: ContentSortFieldModel;
  direction: DirectionModel;
}
