/**
 * Generated by orval v8.20.0 🍺
 * Do not edit manually.
 * Umbraco Management API
 * This shows all APIs available in this version of Umbraco - including all the legacy apis that are available for backward compatibility
 * OpenAPI spec version: Latest
 */
import type { ReferenceByIdModel } from './referenceByIdModel.js';
import type { TemplateQueryExecuteFilterPresentationModel } from './templateQueryExecuteFilterPresentationModel.js';
import type { TemplateQueryExecuteSortModel } from './templateQueryExecuteSortModel.js';

export interface TemplateQueryExecuteModel {
  rootDocument?: null | ReferenceByIdModel;
  /** @nullable */
  documentTypeAlias?: string | null;
  /** @nullable */
  filters?: TemplateQueryExecuteFilterPresentationModel[] | null;
  sort?: null | TemplateQueryExecuteSortModel;
  take: number;
}
