/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Umbraco Management API
 * This shows all APIs available in this version of Umbraco - including all the legacy apis that are available for backward compatibility
 * OpenAPI spec version: Latest
 */
import type { DocumentPermissionPresentationModel } from './documentPermissionPresentationModel.js';
import type { DocumentPropertyValuePermissionPresentationModel } from './documentPropertyValuePermissionPresentationModel.js';
import type { ReferenceByIdModel } from './referenceByIdModel.js';
import type { UnknownTypePermissionPresentationModel } from './unknownTypePermissionPresentationModel.js';

export interface UpdateUserGroupRequestModel {
  name: string;
  alias: string;
  /** @nullable */
  description?: string | null;
  /** @nullable */
  icon?: string | null;
  sections: string[];
  languages: string[];
  hasAccessToAllLanguages: boolean;
  documentStartNode?: ReferenceByIdModel | null;
  documentRootAccess: boolean;
  mediaStartNode?: ReferenceByIdModel | null;
  mediaRootAccess: boolean;
  fallbackPermissions: string[];
  permissions: (DocumentPermissionPresentationModel | DocumentPropertyValuePermissionPresentationModel | UnknownTypePermissionPresentationModel)[];
}
