/**
 * Generated by orval v8.20.0 🍺
 * Do not edit manually.
 * Umbraco Management API
 * This shows all APIs available in this version of Umbraco - including all the legacy apis that are available for backward compatibility
 * OpenAPI spec version: Latest
 */
import type { DocumentTypeCleanupModel } from './documentTypeCleanupModel.js';
import type { DocumentTypeCompositionModel } from './documentTypeCompositionModel.js';
import type { DocumentTypeSortModel } from './documentTypeSortModel.js';
import type { ReferenceByIdModel } from './referenceByIdModel.js';
import type { UpdateDocumentTypePropertyTypeContainerRequestModel } from './updateDocumentTypePropertyTypeContainerRequestModel.js';
import type { UpdateDocumentTypePropertyTypeRequestModel } from './updateDocumentTypePropertyTypeRequestModel.js';

export interface UpdateDocumentTypeRequestModel {
  allowedTemplates: ReferenceByIdModel[];
  defaultTemplate?: null | ReferenceByIdModel;
  cleanup: DocumentTypeCleanupModel;
  allowedDocumentTypes: DocumentTypeSortModel[];
  compositions: DocumentTypeCompositionModel[];
  alias: string;
  name: string;
  /** @nullable */
  description?: string | null;
  icon: string;
  allowedAsRoot: boolean;
  variesByCulture: boolean;
  variesBySegment: boolean;
  collection?: null | ReferenceByIdModel;
  isElement: boolean;
  allowedInLibrary: boolean;
  properties: UpdateDocumentTypePropertyTypeRequestModel[];
  containers: UpdateDocumentTypePropertyTypeContainerRequestModel[];
}
