/**
 * Generated by orval v8.20.0 🍺
 * Do not edit manually.
 * Umbraco Management API
 * This shows all APIs available in this version of Umbraco - including all the legacy apis that are available for backward compatibility
 * OpenAPI spec version: Latest
 */
import type { MemberTypeCompositionModel } from './memberTypeCompositionModel.js';
import type { ReferenceByIdModel } from './referenceByIdModel.js';
import type { UpdateMemberTypePropertyTypeContainerRequestModel } from './updateMemberTypePropertyTypeContainerRequestModel.js';
import type { UpdateMemberTypePropertyTypeRequestModel } from './updateMemberTypePropertyTypeRequestModel.js';

export interface UpdateMemberTypeRequestModel {
  compositions: MemberTypeCompositionModel[];
  alias: string;
  name: string;
  /** @nullable */
  description?: string | null;
  icon: string;
  allowedAsRoot: boolean;
  variesByCulture: boolean;
  variesBySegment: boolean;
  collection?: null | ReferenceByIdModel;
  isElement: boolean;
  allowedInLibrary: boolean;
  properties: UpdateMemberTypePropertyTypeRequestModel[];
  containers: UpdateMemberTypePropertyTypeContainerRequestModel[];
}
