/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Umbraco Management API
 * This shows all APIs available in this version of Umbraco - including all the legacy apis that are available for backward compatibility
 * OpenAPI spec version: Latest
 */

export type UserStateModel = typeof UserStateModel[keyof typeof UserStateModel];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const UserStateModel = {
  Active: 'Active',
  Disabled: 'Disabled',
  LockedOut: 'LockedOut',
  Invited: 'Invited',
  Inactive: 'Inactive',
  All: 'All',
} as const;
