/**
 * Generated by orval v8.17.0 🍺
 * Do not edit manually.
 * Umbraco Management API
 * This shows all APIs available in this version of Umbraco - including all the legacy apis that are available for backward compatibility
 * OpenAPI spec version: Latest
 */
import type { ReferenceByIdModel } from './referenceByIdModel.js';
import type { UserKindModel } from './userKindModel.js';
import type { UserStateModel } from './userStateModel.js';

export interface UserResponseModel {
  id: string;
  /** @nullable */
  languageIsoCode?: string | null;
  documentStartNodeIds: ReferenceByIdModel[];
  hasDocumentRootAccess: boolean;
  mediaStartNodeIds: ReferenceByIdModel[];
  hasMediaRootAccess: boolean;
  elementStartNodeIds: ReferenceByIdModel[];
  hasElementRootAccess: boolean;
  avatarUrls: string[];
  state: UserStateModel;
  failedLoginAttempts: number;
  createDate: string;
  updateDate: string;
  /** @nullable */
  lastLoginDate?: string | null;
  /** @nullable */
  lastLockoutDate?: string | null;
  /** @nullable */
  lastPasswordChangeDate?: string | null;
  isAdmin: boolean;
  kind: UserKindModel;
  email: string;
  userName: string;
  name: string;
  userGroupIds: ReferenceByIdModel[];
}
